// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	auth "github.com/Beigelman/nossas-despesas/internal/modules/auth"
	mock "github.com/stretchr/testify/mock"

	user "github.com/Beigelman/nossas-despesas/internal/modules/user"
)

// MockserviceTokenProvider is an autogenerated mock type for the TokenProvider type
type MockserviceTokenProvider struct {
	mock.Mock
}

type MockserviceTokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockserviceTokenProvider) EXPECT() *MockserviceTokenProvider_Expecter {
	return &MockserviceTokenProvider_Expecter{mock: &_m.Mock}
}

// GenerateUserTokens provides a mock function with given fields: _a0
func (_m *MockserviceTokenProvider) GenerateUserTokens(_a0 user.User) (string, string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GenerateUserTokens")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(user.User) (string, string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(user.User) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(user.User) string); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(user.User) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockserviceTokenProvider_GenerateUserTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateUserTokens'
type MockserviceTokenProvider_GenerateUserTokens_Call struct {
	*mock.Call
}

// GenerateUserTokens is a helper method to define mock.On call
//   - _a0 user.User
func (_e *MockserviceTokenProvider_Expecter) GenerateUserTokens(_a0 interface{}) *MockserviceTokenProvider_GenerateUserTokens_Call {
	return &MockserviceTokenProvider_GenerateUserTokens_Call{Call: _e.mock.On("GenerateUserTokens", _a0)}
}

func (_c *MockserviceTokenProvider_GenerateUserTokens_Call) Run(run func(_a0 user.User)) *MockserviceTokenProvider_GenerateUserTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(user.User))
	})
	return _c
}

func (_c *MockserviceTokenProvider_GenerateUserTokens_Call) Return(_a0 string, _a1 string, _a2 error) *MockserviceTokenProvider_GenerateUserTokens_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockserviceTokenProvider_GenerateUserTokens_Call) RunAndReturn(run func(user.User) (string, string, error)) *MockserviceTokenProvider_GenerateUserTokens_Call {
	_c.Call.Return(run)
	return _c
}

// ParseRefreshToken provides a mock function with given fields: token
func (_m *MockserviceTokenProvider) ParseRefreshToken(token string) (*auth.Token, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseRefreshToken")
	}

	var r0 *auth.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.Token, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.Token); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockserviceTokenProvider_ParseRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseRefreshToken'
type MockserviceTokenProvider_ParseRefreshToken_Call struct {
	*mock.Call
}

// ParseRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *MockserviceTokenProvider_Expecter) ParseRefreshToken(token interface{}) *MockserviceTokenProvider_ParseRefreshToken_Call {
	return &MockserviceTokenProvider_ParseRefreshToken_Call{Call: _e.mock.On("ParseRefreshToken", token)}
}

func (_c *MockserviceTokenProvider_ParseRefreshToken_Call) Run(run func(token string)) *MockserviceTokenProvider_ParseRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockserviceTokenProvider_ParseRefreshToken_Call) Return(_a0 *auth.Token, _a1 error) *MockserviceTokenProvider_ParseRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockserviceTokenProvider_ParseRefreshToken_Call) RunAndReturn(run func(string) (*auth.Token, error)) *MockserviceTokenProvider_ParseRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseToken provides a mock function with given fields: token
func (_m *MockserviceTokenProvider) ParseToken(token string) (*auth.Token, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseToken")
	}

	var r0 *auth.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.Token, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.Token); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockserviceTokenProvider_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type MockserviceTokenProvider_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//   - token string
func (_e *MockserviceTokenProvider_Expecter) ParseToken(token interface{}) *MockserviceTokenProvider_ParseToken_Call {
	return &MockserviceTokenProvider_ParseToken_Call{Call: _e.mock.On("ParseToken", token)}
}

func (_c *MockserviceTokenProvider_ParseToken_Call) Run(run func(token string)) *MockserviceTokenProvider_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockserviceTokenProvider_ParseToken_Call) Return(_a0 *auth.Token, _a1 error) *MockserviceTokenProvider_ParseToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockserviceTokenProvider_ParseToken_Call) RunAndReturn(run func(string) (*auth.Token, error)) *MockserviceTokenProvider_ParseToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockserviceTokenProvider creates a new instance of MockserviceTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockserviceTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockserviceTokenProvider {
	mock := &MockserviceTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
