// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	group "github.com/Beigelman/nossas-despesas/internal/modules/group"
	mock "github.com/stretchr/testify/mock"
)

// MockgroupRepository is an autogenerated mock type for the Repository type
type MockgroupRepository struct {
	mock.Mock
}

type MockgroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockgroupRepository) EXPECT() *MockgroupRepository_Expecter {
	return &MockgroupRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockgroupRepository) GetByID(ctx context.Context, id group.ID) (*group.Group, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *group.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, group.ID) (*group.Group, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, group.ID) *group.Group); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*group.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, group.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockgroupRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockgroupRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id group.ID
func (_e *MockgroupRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockgroupRepository_GetByID_Call {
	return &MockgroupRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockgroupRepository_GetByID_Call) Run(run func(ctx context.Context, id group.ID)) *MockgroupRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(group.ID))
	})
	return _c
}

func (_c *MockgroupRepository_GetByID_Call) Return(_a0 *group.Group, _a1 error) *MockgroupRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockgroupRepository_GetByID_Call) RunAndReturn(run func(context.Context, group.ID) (*group.Group, error)) *MockgroupRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockgroupRepository) GetByName(ctx context.Context, name string) (*group.Group, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *group.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*group.Group, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *group.Group); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*group.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockgroupRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockgroupRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockgroupRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockgroupRepository_GetByName_Call {
	return &MockgroupRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockgroupRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockgroupRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockgroupRepository_GetByName_Call) Return(_a0 *group.Group, _a1 error) *MockgroupRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockgroupRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*group.Group, error)) *MockgroupRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockgroupRepository) GetNextID() group.ID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNextID")
	}

	var r0 group.ID
	if rf, ok := ret.Get(0).(func() group.ID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(group.ID)
	}

	return r0
}

// MockgroupRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockgroupRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockgroupRepository_Expecter) GetNextID() *MockgroupRepository_GetNextID_Call {
	return &MockgroupRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockgroupRepository_GetNextID_Call) Run(run func()) *MockgroupRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockgroupRepository_GetNextID_Call) Return(_a0 group.ID) *MockgroupRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockgroupRepository_GetNextID_Call) RunAndReturn(run func() group.ID) *MockgroupRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, entity
func (_m *MockgroupRepository) Store(ctx context.Context, entity *group.Group) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *group.Group) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockgroupRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockgroupRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *group.Group
func (_e *MockgroupRepository_Expecter) Store(ctx interface{}, entity interface{}) *MockgroupRepository_Store_Call {
	return &MockgroupRepository_Store_Call{Call: _e.mock.On("Store", ctx, entity)}
}

func (_c *MockgroupRepository_Store_Call) Run(run func(ctx context.Context, entity *group.Group)) *MockgroupRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*group.Group))
	})
	return _c
}

func (_c *MockgroupRepository_Store_Call) Return(_a0 error) *MockgroupRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockgroupRepository_Store_Call) RunAndReturn(run func(context.Context, *group.Group) error) *MockgroupRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockgroupRepository creates a new instance of MockgroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockgroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockgroupRepository {
	mock := &MockgroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
