// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	group "github.com/Beigelman/nossas-despesas/internal/modules/group"
	mock "github.com/stretchr/testify/mock"
)

// MockgroupInviteRepository is an autogenerated mock type for the InviteRepository type
type MockgroupInviteRepository struct {
	mock.Mock
}

type MockgroupInviteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockgroupInviteRepository) EXPECT() *MockgroupInviteRepository_Expecter {
	return &MockgroupInviteRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockgroupInviteRepository) GetByID(ctx context.Context, id group.InviteID) (*group.Invite, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *group.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, group.InviteID) (*group.Invite, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, group.InviteID) *group.Invite); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*group.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, group.InviteID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockgroupInviteRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockgroupInviteRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id group.InviteID
func (_e *MockgroupInviteRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockgroupInviteRepository_GetByID_Call {
	return &MockgroupInviteRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockgroupInviteRepository_GetByID_Call) Run(run func(ctx context.Context, id group.InviteID)) *MockgroupInviteRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(group.InviteID))
	})
	return _c
}

func (_c *MockgroupInviteRepository_GetByID_Call) Return(_a0 *group.Invite, _a1 error) *MockgroupInviteRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockgroupInviteRepository_GetByID_Call) RunAndReturn(run func(context.Context, group.InviteID) (*group.Invite, error)) *MockgroupInviteRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByToken provides a mock function with given fields: ctx, token
func (_m *MockgroupInviteRepository) GetByToken(ctx context.Context, token string) (*group.Invite, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetByToken")
	}

	var r0 *group.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*group.Invite, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *group.Invite); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*group.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockgroupInviteRepository_GetByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByToken'
type MockgroupInviteRepository_GetByToken_Call struct {
	*mock.Call
}

// GetByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockgroupInviteRepository_Expecter) GetByToken(ctx interface{}, token interface{}) *MockgroupInviteRepository_GetByToken_Call {
	return &MockgroupInviteRepository_GetByToken_Call{Call: _e.mock.On("GetByToken", ctx, token)}
}

func (_c *MockgroupInviteRepository_GetByToken_Call) Run(run func(ctx context.Context, token string)) *MockgroupInviteRepository_GetByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockgroupInviteRepository_GetByToken_Call) Return(_a0 *group.Invite, _a1 error) *MockgroupInviteRepository_GetByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockgroupInviteRepository_GetByToken_Call) RunAndReturn(run func(context.Context, string) (*group.Invite, error)) *MockgroupInviteRepository_GetByToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupInvitesByEmail provides a mock function with given fields: ctx, groupID, email
func (_m *MockgroupInviteRepository) GetGroupInvitesByEmail(ctx context.Context, groupID group.ID, email string) ([]group.Invite, error) {
	ret := _m.Called(ctx, groupID, email)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupInvitesByEmail")
	}

	var r0 []group.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, group.ID, string) ([]group.Invite, error)); ok {
		return rf(ctx, groupID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, group.ID, string) []group.Invite); ok {
		r0 = rf(ctx, groupID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]group.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, group.ID, string) error); ok {
		r1 = rf(ctx, groupID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockgroupInviteRepository_GetGroupInvitesByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupInvitesByEmail'
type MockgroupInviteRepository_GetGroupInvitesByEmail_Call struct {
	*mock.Call
}

// GetGroupInvitesByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID group.ID
//   - email string
func (_e *MockgroupInviteRepository_Expecter) GetGroupInvitesByEmail(ctx interface{}, groupID interface{}, email interface{}) *MockgroupInviteRepository_GetGroupInvitesByEmail_Call {
	return &MockgroupInviteRepository_GetGroupInvitesByEmail_Call{Call: _e.mock.On("GetGroupInvitesByEmail", ctx, groupID, email)}
}

func (_c *MockgroupInviteRepository_GetGroupInvitesByEmail_Call) Run(run func(ctx context.Context, groupID group.ID, email string)) *MockgroupInviteRepository_GetGroupInvitesByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(group.ID), args[2].(string))
	})
	return _c
}

func (_c *MockgroupInviteRepository_GetGroupInvitesByEmail_Call) Return(_a0 []group.Invite, _a1 error) *MockgroupInviteRepository_GetGroupInvitesByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockgroupInviteRepository_GetGroupInvitesByEmail_Call) RunAndReturn(run func(context.Context, group.ID, string) ([]group.Invite, error)) *MockgroupInviteRepository_GetGroupInvitesByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockgroupInviteRepository) GetNextID() group.InviteID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNextID")
	}

	var r0 group.InviteID
	if rf, ok := ret.Get(0).(func() group.InviteID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(group.InviteID)
	}

	return r0
}

// MockgroupInviteRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockgroupInviteRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockgroupInviteRepository_Expecter) GetNextID() *MockgroupInviteRepository_GetNextID_Call {
	return &MockgroupInviteRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockgroupInviteRepository_GetNextID_Call) Run(run func()) *MockgroupInviteRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockgroupInviteRepository_GetNextID_Call) Return(_a0 group.InviteID) *MockgroupInviteRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockgroupInviteRepository_GetNextID_Call) RunAndReturn(run func() group.InviteID) *MockgroupInviteRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, entity
func (_m *MockgroupInviteRepository) Store(ctx context.Context, entity *group.Invite) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *group.Invite) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockgroupInviteRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockgroupInviteRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *group.Invite
func (_e *MockgroupInviteRepository_Expecter) Store(ctx interface{}, entity interface{}) *MockgroupInviteRepository_Store_Call {
	return &MockgroupInviteRepository_Store_Call{Call: _e.mock.On("Store", ctx, entity)}
}

func (_c *MockgroupInviteRepository_Store_Call) Run(run func(ctx context.Context, entity *group.Invite)) *MockgroupInviteRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*group.Invite))
	})
	return _c
}

func (_c *MockgroupInviteRepository_Store_Call) Return(_a0 error) *MockgroupInviteRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockgroupInviteRepository_Store_Call) RunAndReturn(run func(context.Context, *group.Invite) error) *MockgroupInviteRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockgroupInviteRepository creates a new instance of MockgroupInviteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockgroupInviteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockgroupInviteRepository {
	mock := &MockgroupInviteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
