// Code generated by mockery v2.23.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Beigelman/ludaapi/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockCreateGroup is an autogenerated mock type for the CreateGroup type
type MockCreateGroup struct {
	mock.Mock
}

type MockCreateGroup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateGroup) EXPECT() *MockCreateGroup_Expecter {
	return &MockCreateGroup_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, name
func (_m *MockCreateGroup) Execute(ctx context.Context, name string) (*entity.Group, error) {
	ret := _m.Called(ctx, name)

	var r0 *entity.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Group, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Group); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateGroup_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateGroup_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCreateGroup_Expecter) Execute(ctx interface{}, name interface{}) *MockCreateGroup_Execute_Call {
	return &MockCreateGroup_Execute_Call{Call: _e.mock.On("Execute", ctx, name)}
}

func (_c *MockCreateGroup_Execute_Call) Run(run func(ctx context.Context, name string)) *MockCreateGroup_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCreateGroup_Execute_Call) Return(_a0 *entity.Group, _a1 error) *MockCreateGroup_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateGroup_Execute_Call) RunAndReturn(run func(context.Context, string) (*entity.Group, error)) *MockCreateGroup_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateGroup creates a new instance of MockCreateGroup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateGroup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateGroup {
	mock := &MockCreateGroup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
