with-expecter: true
all: true
dir: internal/shared/mocks
outpkg: mocks
mockname: "Mock{{.PackageName}}{{.InterfaceName}}"
filename: "mock_{{.PackageName}}_{{.InterfaceName}}.go"
packages:
  github.com/Beigelman/nossas-despesas/internal/modules/auth:
  github.com/Beigelman/nossas-despesas/internal/modules/auth/usecase:
  github.com/Beigelman/nossas-despesas/internal/modules/category:
  github.com/Beigelman/nossas-despesas/internal/modules/category/usecase:
  github.com/Beigelman/nossas-despesas/internal/modules/expense:
  github.com/Beigelman/nossas-despesas/internal/modules/expense/usecase:
  github.com/Beigelman/nossas-despesas/internal/modules/group:
  github.com/Beigelman/nossas-despesas/internal/modules/group/usecase:
  github.com/Beigelman/nossas-despesas/internal/modules/income:
  github.com/Beigelman/nossas-despesas/internal/modules/income/usecase:
  github.com/Beigelman/nossas-despesas/internal/modules/user:
  github.com/Beigelman/nossas-despesas/internal/modules/user/usecase:
  github.com/Beigelman/nossas-despesas/internal/shared/service:
  github.com/Beigelman/nossas-despesas/internal/pkg/pubsub:
