with-expecter: true
all: true
dir: internal/tests/mocks/{{.PackageName}}
outpkg: mock{{.PackageName}}
filename: "mock_{{.InterfaceName}}.go"
packages:
  github.com/Beigelman/nossas-despesas/internal/domain/repository:
  github.com/Beigelman/nossas-despesas/internal/domain/service:
  github.com/Beigelman/nossas-despesas/internal/modules/user:
  github.com/Beigelman/nossas-despesas/internal/modules/user/usecase:
  github.com/Beigelman/nossas-despesas/internal/usecase: