with-expecter: true
all: true
dir: internal/tests/mocks
outpkg: mocks
filename: "mock_{{.PackageName}}_{{.InterfaceName}}.go"
packages:
  github.com/Beigelman/ludaapi/internal/domain/repository:
  github.com/Beigelman/ludaapi/internal/usecase: