version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - errname
    - errorlint
    - funlen
    - gocognit
    - grouper
    - misspell
    - nestif
    - nilerr
    - nolintlint
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
  settings:
    funlen:
      lines: 150
      statements: 55
      ignore-comments: true
    govet:
      enable:
        - nilness
    nestif:
      min-complexity: 7
    gocognit:
      min-complexity: 80
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
        path: _test\.go
      - linters:
          - sqlclosecheck
        path: internal/pkg/db/client.go
      - linters:
          - staticcheck
        text: "SA3000:"
    paths:
      - internal/shared/mocks
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/Beigelman/nossas-despesas)
  exclusions:
    generated: lax
    paths:
      - internal/shared/mocks
      - third_party$
      - builtin$
      - examples$
