// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	income "github.com/Beigelman/nossas-despesas/internal/modules/income"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/income/usecase"
)

// MockusecaseDeleteIncome is an autogenerated mock type for the DeleteIncome type
type MockusecaseDeleteIncome struct {
	mock.Mock
}

type MockusecaseDeleteIncome_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseDeleteIncome) EXPECT() *MockusecaseDeleteIncome_Expecter {
	return &MockusecaseDeleteIncome_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockusecaseDeleteIncome) Execute(ctx context.Context, p usecase.DeleteIncomeParams) (*income.Income, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *income.Income
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.DeleteIncomeParams) (*income.Income, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.DeleteIncomeParams) *income.Income); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*income.Income)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.DeleteIncomeParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseDeleteIncome_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseDeleteIncome_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.DeleteIncomeParams
func (_e *MockusecaseDeleteIncome_Expecter) Execute(ctx interface{}, p interface{}) *MockusecaseDeleteIncome_Execute_Call {
	return &MockusecaseDeleteIncome_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockusecaseDeleteIncome_Execute_Call) Run(run func(ctx context.Context, p usecase.DeleteIncomeParams)) *MockusecaseDeleteIncome_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.DeleteIncomeParams))
	})
	return _c
}

func (_c *MockusecaseDeleteIncome_Execute_Call) Return(_a0 *income.Income, _a1 error) *MockusecaseDeleteIncome_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecaseDeleteIncome_Execute_Call) RunAndReturn(run func(context.Context, usecase.DeleteIncomeParams) (*income.Income, error)) *MockusecaseDeleteIncome_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseDeleteIncome creates a new instance of MockusecaseDeleteIncome. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseDeleteIncome(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseDeleteIncome {
	mock := &MockusecaseDeleteIncome{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
