// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	expense "github.com/Beigelman/nossas-despesas/internal/modules/expense"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/expense/usecase"
)

// MockusecaseUpdateExpense is an autogenerated mock type for the UpdateExpense type
type MockusecaseUpdateExpense struct {
	mock.Mock
}

type MockusecaseUpdateExpense_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseUpdateExpense) EXPECT() *MockusecaseUpdateExpense_Expecter {
	return &MockusecaseUpdateExpense_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockusecaseUpdateExpense) Execute(ctx context.Context, p usecase.UpdateExpenseParams) (*expense.Expense, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *expense.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UpdateExpenseParams) (*expense.Expense, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UpdateExpenseParams) *expense.Expense); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.UpdateExpenseParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseUpdateExpense_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseUpdateExpense_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.UpdateExpenseParams
func (_e *MockusecaseUpdateExpense_Expecter) Execute(ctx interface{}, p interface{}) *MockusecaseUpdateExpense_Execute_Call {
	return &MockusecaseUpdateExpense_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockusecaseUpdateExpense_Execute_Call) Run(run func(ctx context.Context, p usecase.UpdateExpenseParams)) *MockusecaseUpdateExpense_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.UpdateExpenseParams))
	})
	return _c
}

func (_c *MockusecaseUpdateExpense_Execute_Call) Return(_a0 *expense.Expense, _a1 error) *MockusecaseUpdateExpense_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecaseUpdateExpense_Execute_Call) RunAndReturn(run func(context.Context, usecase.UpdateExpenseParams) (*expense.Expense, error)) *MockusecaseUpdateExpense_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseUpdateExpense creates a new instance of MockusecaseUpdateExpense. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseUpdateExpense(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseUpdateExpense {
	mock := &MockusecaseUpdateExpense{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
