// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	category "github.com/Beigelman/nossas-despesas/internal/modules/category"

	mock "github.com/stretchr/testify/mock"
)

// MockcategoryRepository is an autogenerated mock type for the Repository type
type MockcategoryRepository struct {
	mock.Mock
}

type MockcategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockcategoryRepository) EXPECT() *MockcategoryRepository_Expecter {
	return &MockcategoryRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockcategoryRepository) GetByID(ctx context.Context, id category.ID) (*category.Category, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *category.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, category.ID) (*category.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, category.ID) *category.Category); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, category.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockcategoryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockcategoryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id category.ID
func (_e *MockcategoryRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockcategoryRepository_GetByID_Call {
	return &MockcategoryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockcategoryRepository_GetByID_Call) Run(run func(ctx context.Context, id category.ID)) *MockcategoryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(category.ID))
	})
	return _c
}

func (_c *MockcategoryRepository_GetByID_Call) Return(_a0 *category.Category, _a1 error) *MockcategoryRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockcategoryRepository_GetByID_Call) RunAndReturn(run func(context.Context, category.ID) (*category.Category, error)) *MockcategoryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockcategoryRepository) GetByName(ctx context.Context, name string) (*category.Category, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *category.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*category.Category, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *category.Category); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockcategoryRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockcategoryRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockcategoryRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockcategoryRepository_GetByName_Call {
	return &MockcategoryRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockcategoryRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockcategoryRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockcategoryRepository_GetByName_Call) Return(_a0 *category.Category, _a1 error) *MockcategoryRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockcategoryRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*category.Category, error)) *MockcategoryRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with no fields
func (_m *MockcategoryRepository) GetNextID() category.ID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNextID")
	}

	var r0 category.ID
	if rf, ok := ret.Get(0).(func() category.ID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(category.ID)
	}

	return r0
}

// MockcategoryRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockcategoryRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockcategoryRepository_Expecter) GetNextID() *MockcategoryRepository_GetNextID_Call {
	return &MockcategoryRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockcategoryRepository_GetNextID_Call) Run(run func()) *MockcategoryRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockcategoryRepository_GetNextID_Call) Return(_a0 category.ID) *MockcategoryRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockcategoryRepository_GetNextID_Call) RunAndReturn(run func() category.ID) *MockcategoryRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, entity
func (_m *MockcategoryRepository) Store(ctx context.Context, entity *category.Category) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *category.Category) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockcategoryRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockcategoryRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *category.Category
func (_e *MockcategoryRepository_Expecter) Store(ctx interface{}, entity interface{}) *MockcategoryRepository_Store_Call {
	return &MockcategoryRepository_Store_Call{Call: _e.mock.On("Store", ctx, entity)}
}

func (_c *MockcategoryRepository_Store_Call) Run(run func(ctx context.Context, entity *category.Category)) *MockcategoryRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*category.Category))
	})
	return _c
}

func (_c *MockcategoryRepository_Store_Call) Return(_a0 error) *MockcategoryRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockcategoryRepository_Store_Call) RunAndReturn(run func(context.Context, *category.Category) error) *MockcategoryRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockcategoryRepository creates a new instance of MockcategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockcategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockcategoryRepository {
	mock := &MockcategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
