// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	group "github.com/Beigelman/nossas-despesas/internal/modules/group"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/group/usecase"
)

// MockusecaseCreateGroup is an autogenerated mock type for the CreateGroup type
type MockusecaseCreateGroup struct {
	mock.Mock
}

type MockusecaseCreateGroup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseCreateGroup) EXPECT() *MockusecaseCreateGroup_Expecter {
	return &MockusecaseCreateGroup_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, params
func (_m *MockusecaseCreateGroup) Execute(ctx context.Context, params usecase.CreateGroupInput) (*group.Group, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *group.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateGroupInput) (*group.Group, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateGroupInput) *group.Group); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*group.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreateGroupInput) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseCreateGroup_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseCreateGroup_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - params usecase.CreateGroupInput
func (_e *MockusecaseCreateGroup_Expecter) Execute(ctx interface{}, params interface{}) *MockusecaseCreateGroup_Execute_Call {
	return &MockusecaseCreateGroup_Execute_Call{Call: _e.mock.On("Execute", ctx, params)}
}

func (_c *MockusecaseCreateGroup_Execute_Call) Run(run func(ctx context.Context, params usecase.CreateGroupInput)) *MockusecaseCreateGroup_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateGroupInput))
	})
	return _c
}

func (_c *MockusecaseCreateGroup_Execute_Call) Return(_a0 *group.Group, _a1 error) *MockusecaseCreateGroup_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecaseCreateGroup_Execute_Call) RunAndReturn(run func(context.Context, usecase.CreateGroupInput) (*group.Group, error)) *MockusecaseCreateGroup_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseCreateGroup creates a new instance of MockusecaseCreateGroup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseCreateGroup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseCreateGroup {
	mock := &MockusecaseCreateGroup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
