// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	email "github.com/Beigelman/nossas-despesas/internal/pkg/email"
	mock "github.com/stretchr/testify/mock"
)

// MockserviceEmailProvider is an autogenerated mock type for the EmailProvider type
type MockserviceEmailProvider struct {
	mock.Mock
}

type MockserviceEmailProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockserviceEmailProvider) EXPECT() *MockserviceEmailProvider_Expecter {
	return &MockserviceEmailProvider_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, _a1
func (_m *MockserviceEmailProvider) Send(ctx context.Context, _a1 email.Email) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, email.Email) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockserviceEmailProvider_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockserviceEmailProvider_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 email.Email
func (_e *MockserviceEmailProvider_Expecter) Send(ctx interface{}, _a1 interface{}) *MockserviceEmailProvider_Send_Call {
	return &MockserviceEmailProvider_Send_Call{Call: _e.mock.On("Send", ctx, _a1)}
}

func (_c *MockserviceEmailProvider_Send_Call) Run(run func(ctx context.Context, _a1 email.Email)) *MockserviceEmailProvider_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(email.Email))
	})
	return _c
}

func (_c *MockserviceEmailProvider_Send_Call) Return(_a0 error) *MockserviceEmailProvider_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockserviceEmailProvider_Send_Call) RunAndReturn(run func(context.Context, email.Email) error) *MockserviceEmailProvider_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockserviceEmailProvider creates a new instance of MockserviceEmailProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockserviceEmailProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockserviceEmailProvider {
	mock := &MockserviceEmailProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
