// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockservicePredicter is an autogenerated mock type for the Predicter type
type MockservicePredicter struct {
	mock.Mock
}

type MockservicePredicter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockservicePredicter) EXPECT() *MockservicePredicter_Expecter {
	return &MockservicePredicter_Expecter{mock: &_m.Mock}
}

// ExpenseCategory provides a mock function with given fields: ctx, name, amount
func (_m *MockservicePredicter) ExpenseCategory(ctx context.Context, name string, amount int) (int, error) {
	ret := _m.Called(ctx, name, amount)

	if len(ret) == 0 {
		panic("no return value specified for ExpenseCategory")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (int, error)); ok {
		return rf(ctx, name, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) int); ok {
		r0 = rf(ctx, name, amount)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, name, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockservicePredicter_ExpenseCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpenseCategory'
type MockservicePredicter_ExpenseCategory_Call struct {
	*mock.Call
}

// ExpenseCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - amount int
func (_e *MockservicePredicter_Expecter) ExpenseCategory(ctx interface{}, name interface{}, amount interface{}) *MockservicePredicter_ExpenseCategory_Call {
	return &MockservicePredicter_ExpenseCategory_Call{Call: _e.mock.On("ExpenseCategory", ctx, name, amount)}
}

func (_c *MockservicePredicter_ExpenseCategory_Call) Run(run func(ctx context.Context, name string, amount int)) *MockservicePredicter_ExpenseCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockservicePredicter_ExpenseCategory_Call) Return(categoryID int, err error) *MockservicePredicter_ExpenseCategory_Call {
	_c.Call.Return(categoryID, err)
	return _c
}

func (_c *MockservicePredicter_ExpenseCategory_Call) RunAndReturn(run func(context.Context, string, int) (int, error)) *MockservicePredicter_ExpenseCategory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockservicePredicter creates a new instance of MockservicePredicter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockservicePredicter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockservicePredicter {
	mock := &MockservicePredicter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
