// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	message "github.com/ThreeDotsLabs/watermill/message"
	mock "github.com/stretchr/testify/mock"
)

// MockpubsubSubscriber is an autogenerated mock type for the Subscriber type
type MockpubsubSubscriber struct {
	mock.Mock
}

type MockpubsubSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockpubsubSubscriber) EXPECT() *MockpubsubSubscriber_Expecter {
	return &MockpubsubSubscriber_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockpubsubSubscriber) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockpubsubSubscriber_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockpubsubSubscriber_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockpubsubSubscriber_Expecter) Close() *MockpubsubSubscriber_Close_Call {
	return &MockpubsubSubscriber_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockpubsubSubscriber_Close_Call) Run(run func()) *MockpubsubSubscriber_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockpubsubSubscriber_Close_Call) Return(_a0 error) *MockpubsubSubscriber_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockpubsubSubscriber_Close_Call) RunAndReturn(run func() error) *MockpubsubSubscriber_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, topic
func (_m *MockpubsubSubscriber) Subscribe(ctx context.Context, topic string) (<-chan *message.Message, error) {
	ret := _m.Called(ctx, topic)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan *message.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (<-chan *message.Message, error)); ok {
		return rf(ctx, topic)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan *message.Message); ok {
		r0 = rf(ctx, topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *message.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, topic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockpubsubSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockpubsubSubscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
func (_e *MockpubsubSubscriber_Expecter) Subscribe(ctx interface{}, topic interface{}) *MockpubsubSubscriber_Subscribe_Call {
	return &MockpubsubSubscriber_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, topic)}
}

func (_c *MockpubsubSubscriber_Subscribe_Call) Run(run func(ctx context.Context, topic string)) *MockpubsubSubscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockpubsubSubscriber_Subscribe_Call) Return(_a0 <-chan *message.Message, _a1 error) *MockpubsubSubscriber_Subscribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockpubsubSubscriber_Subscribe_Call) RunAndReturn(run func(context.Context, string) (<-chan *message.Message, error)) *MockpubsubSubscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockpubsubSubscriber creates a new instance of MockpubsubSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockpubsubSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockpubsubSubscriber {
	mock := &MockpubsubSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
