// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/auth/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockusecaseRefreshAuthToken is an autogenerated mock type for the RefreshAuthToken type
type MockusecaseRefreshAuthToken struct {
	mock.Mock
}

type MockusecaseRefreshAuthToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseRefreshAuthToken) EXPECT() *MockusecaseRefreshAuthToken_Expecter {
	return &MockusecaseRefreshAuthToken_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockusecaseRefreshAuthToken) Execute(ctx context.Context, p usecase.RefreshAuthTokenParams) (*usecase.RefreshAuthTokenResponse, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *usecase.RefreshAuthTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RefreshAuthTokenParams) (*usecase.RefreshAuthTokenResponse, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RefreshAuthTokenParams) *usecase.RefreshAuthTokenResponse); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.RefreshAuthTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.RefreshAuthTokenParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseRefreshAuthToken_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseRefreshAuthToken_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.RefreshAuthTokenParams
func (_e *MockusecaseRefreshAuthToken_Expecter) Execute(ctx interface{}, p interface{}) *MockusecaseRefreshAuthToken_Execute_Call {
	return &MockusecaseRefreshAuthToken_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockusecaseRefreshAuthToken_Execute_Call) Run(run func(ctx context.Context, p usecase.RefreshAuthTokenParams)) *MockusecaseRefreshAuthToken_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.RefreshAuthTokenParams))
	})
	return _c
}

func (_c *MockusecaseRefreshAuthToken_Execute_Call) Return(_a0 *usecase.RefreshAuthTokenResponse, _a1 error) *MockusecaseRefreshAuthToken_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecaseRefreshAuthToken_Execute_Call) RunAndReturn(run func(context.Context, usecase.RefreshAuthTokenParams) (*usecase.RefreshAuthTokenResponse, error)) *MockusecaseRefreshAuthToken_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseRefreshAuthToken creates a new instance of MockusecaseRefreshAuthToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseRefreshAuthToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseRefreshAuthToken {
	mock := &MockusecaseRefreshAuthToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
