// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	category "github.com/Beigelman/nossas-despesas/internal/modules/category"

	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/category/usecase"
)

// MockusecaseCreateCategory is an autogenerated mock type for the CreateCategory type
type MockusecaseCreateCategory struct {
	mock.Mock
}

type MockusecaseCreateCategory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseCreateCategory) EXPECT() *MockusecaseCreateCategory_Expecter {
	return &MockusecaseCreateCategory_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockusecaseCreateCategory) Execute(ctx context.Context, input usecase.CreateCategoryInput) (*category.Category, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *category.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateCategoryInput) (*category.Category, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateCategoryInput) *category.Category); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreateCategoryInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseCreateCategory_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseCreateCategory_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.CreateCategoryInput
func (_e *MockusecaseCreateCategory_Expecter) Execute(ctx interface{}, input interface{}) *MockusecaseCreateCategory_Execute_Call {
	return &MockusecaseCreateCategory_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockusecaseCreateCategory_Execute_Call) Run(run func(ctx context.Context, input usecase.CreateCategoryInput)) *MockusecaseCreateCategory_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateCategoryInput))
	})
	return _c
}

func (_c *MockusecaseCreateCategory_Execute_Call) Return(_a0 *category.Category, _a1 error) *MockusecaseCreateCategory_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecaseCreateCategory_Execute_Call) RunAndReturn(run func(context.Context, usecase.CreateCategoryInput) (*category.Category, error)) *MockusecaseCreateCategory_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseCreateCategory creates a new instance of MockusecaseCreateCategory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseCreateCategory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseCreateCategory {
	mock := &MockusecaseCreateCategory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
