// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/expense/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockusecasePredictExpenseCategory is an autogenerated mock type for the PredictExpenseCategory type
type MockusecasePredictExpenseCategory struct {
	mock.Mock
}

type MockusecasePredictExpenseCategory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecasePredictExpenseCategory) EXPECT() *MockusecasePredictExpenseCategory_Expecter {
	return &MockusecasePredictExpenseCategory_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockusecasePredictExpenseCategory) Execute(ctx context.Context, input usecase.PredictExpenseCategoryInput) (int, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.PredictExpenseCategoryInput) (int, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.PredictExpenseCategoryInput) int); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.PredictExpenseCategoryInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecasePredictExpenseCategory_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecasePredictExpenseCategory_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.PredictExpenseCategoryInput
func (_e *MockusecasePredictExpenseCategory_Expecter) Execute(ctx interface{}, input interface{}) *MockusecasePredictExpenseCategory_Execute_Call {
	return &MockusecasePredictExpenseCategory_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockusecasePredictExpenseCategory_Execute_Call) Run(run func(ctx context.Context, input usecase.PredictExpenseCategoryInput)) *MockusecasePredictExpenseCategory_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.PredictExpenseCategoryInput))
	})
	return _c
}

func (_c *MockusecasePredictExpenseCategory_Execute_Call) Return(_a0 int, _a1 error) *MockusecasePredictExpenseCategory_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecasePredictExpenseCategory_Execute_Call) RunAndReturn(run func(context.Context, usecase.PredictExpenseCategoryInput) (int, error)) *MockusecasePredictExpenseCategory_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecasePredictExpenseCategory creates a new instance of MockusecasePredictExpenseCategory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecasePredictExpenseCategory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecasePredictExpenseCategory {
	mock := &MockusecasePredictExpenseCategory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
