// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	expense "github.com/Beigelman/nossas-despesas/internal/modules/expense"
	mock "github.com/stretchr/testify/mock"
)

// MockusecaseDeleteExpense is an autogenerated mock type for the DeleteExpense type
type MockusecaseDeleteExpense struct {
	mock.Mock
}

type MockusecaseDeleteExpense_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseDeleteExpense) EXPECT() *MockusecaseDeleteExpense_Expecter {
	return &MockusecaseDeleteExpense_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, expenseID
func (_m *MockusecaseDeleteExpense) Execute(ctx context.Context, expenseID expense.ID) (*expense.Expense, error) {
	ret := _m.Called(ctx, expenseID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *expense.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, expense.ID) (*expense.Expense, error)); ok {
		return rf(ctx, expenseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, expense.ID) *expense.Expense); ok {
		r0 = rf(ctx, expenseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, expense.ID) error); ok {
		r1 = rf(ctx, expenseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseDeleteExpense_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseDeleteExpense_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - expenseID expense.ID
func (_e *MockusecaseDeleteExpense_Expecter) Execute(ctx interface{}, expenseID interface{}) *MockusecaseDeleteExpense_Execute_Call {
	return &MockusecaseDeleteExpense_Execute_Call{Call: _e.mock.On("Execute", ctx, expenseID)}
}

func (_c *MockusecaseDeleteExpense_Execute_Call) Run(run func(ctx context.Context, expenseID expense.ID)) *MockusecaseDeleteExpense_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(expense.ID))
	})
	return _c
}

func (_c *MockusecaseDeleteExpense_Execute_Call) Return(_a0 *expense.Expense, _a1 error) *MockusecaseDeleteExpense_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecaseDeleteExpense_Execute_Call) RunAndReturn(run func(context.Context, expense.ID) (*expense.Expense, error)) *MockusecaseDeleteExpense_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseDeleteExpense creates a new instance of MockusecaseDeleteExpense. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseDeleteExpense(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseDeleteExpense {
	mock := &MockusecaseDeleteExpense{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
