// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	category "github.com/Beigelman/nossas-despesas/internal/modules/category"

	mock "github.com/stretchr/testify/mock"
)

// MockcategoryGroupRepository is an autogenerated mock type for the GroupRepository type
type MockcategoryGroupRepository struct {
	mock.Mock
}

type MockcategoryGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockcategoryGroupRepository) EXPECT() *MockcategoryGroupRepository_Expecter {
	return &MockcategoryGroupRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockcategoryGroupRepository) GetByID(ctx context.Context, id category.GroupID) (*category.Group, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *category.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, category.GroupID) (*category.Group, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, category.GroupID) *category.Group); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, category.GroupID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockcategoryGroupRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockcategoryGroupRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id category.GroupID
func (_e *MockcategoryGroupRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockcategoryGroupRepository_GetByID_Call {
	return &MockcategoryGroupRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockcategoryGroupRepository_GetByID_Call) Run(run func(ctx context.Context, id category.GroupID)) *MockcategoryGroupRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(category.GroupID))
	})
	return _c
}

func (_c *MockcategoryGroupRepository_GetByID_Call) Return(_a0 *category.Group, _a1 error) *MockcategoryGroupRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockcategoryGroupRepository_GetByID_Call) RunAndReturn(run func(context.Context, category.GroupID) (*category.Group, error)) *MockcategoryGroupRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockcategoryGroupRepository) GetByName(ctx context.Context, name string) (*category.Group, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *category.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*category.Group, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *category.Group); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockcategoryGroupRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockcategoryGroupRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockcategoryGroupRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockcategoryGroupRepository_GetByName_Call {
	return &MockcategoryGroupRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockcategoryGroupRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockcategoryGroupRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockcategoryGroupRepository_GetByName_Call) Return(_a0 *category.Group, _a1 error) *MockcategoryGroupRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockcategoryGroupRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*category.Group, error)) *MockcategoryGroupRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with no fields
func (_m *MockcategoryGroupRepository) GetNextID() category.GroupID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNextID")
	}

	var r0 category.GroupID
	if rf, ok := ret.Get(0).(func() category.GroupID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(category.GroupID)
	}

	return r0
}

// MockcategoryGroupRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockcategoryGroupRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockcategoryGroupRepository_Expecter) GetNextID() *MockcategoryGroupRepository_GetNextID_Call {
	return &MockcategoryGroupRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockcategoryGroupRepository_GetNextID_Call) Run(run func()) *MockcategoryGroupRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockcategoryGroupRepository_GetNextID_Call) Return(_a0 category.GroupID) *MockcategoryGroupRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockcategoryGroupRepository_GetNextID_Call) RunAndReturn(run func() category.GroupID) *MockcategoryGroupRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, entity
func (_m *MockcategoryGroupRepository) Store(ctx context.Context, entity *category.Group) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *category.Group) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockcategoryGroupRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockcategoryGroupRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *category.Group
func (_e *MockcategoryGroupRepository_Expecter) Store(ctx interface{}, entity interface{}) *MockcategoryGroupRepository_Store_Call {
	return &MockcategoryGroupRepository_Store_Call{Call: _e.mock.On("Store", ctx, entity)}
}

func (_c *MockcategoryGroupRepository_Store_Call) Run(run func(ctx context.Context, entity *category.Group)) *MockcategoryGroupRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*category.Group))
	})
	return _c
}

func (_c *MockcategoryGroupRepository_Store_Call) Return(_a0 error) *MockcategoryGroupRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockcategoryGroupRepository_Store_Call) RunAndReturn(run func(context.Context, *category.Group) error) *MockcategoryGroupRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockcategoryGroupRepository creates a new instance of MockcategoryGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockcategoryGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockcategoryGroupRepository {
	mock := &MockcategoryGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
