// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/auth/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockusecaseSignInWithGoogle is an autogenerated mock type for the SignInWithGoogle type
type MockusecaseSignInWithGoogle struct {
	mock.Mock
}

type MockusecaseSignInWithGoogle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseSignInWithGoogle) EXPECT() *MockusecaseSignInWithGoogle_Expecter {
	return &MockusecaseSignInWithGoogle_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockusecaseSignInWithGoogle) Execute(ctx context.Context, p usecase.SignInWithGoogleParams) (*usecase.SignInWithGoogleResponse, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *usecase.SignInWithGoogleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.SignInWithGoogleParams) (*usecase.SignInWithGoogleResponse, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.SignInWithGoogleParams) *usecase.SignInWithGoogleResponse); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.SignInWithGoogleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.SignInWithGoogleParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseSignInWithGoogle_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseSignInWithGoogle_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.SignInWithGoogleParams
func (_e *MockusecaseSignInWithGoogle_Expecter) Execute(ctx interface{}, p interface{}) *MockusecaseSignInWithGoogle_Execute_Call {
	return &MockusecaseSignInWithGoogle_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockusecaseSignInWithGoogle_Execute_Call) Run(run func(ctx context.Context, p usecase.SignInWithGoogleParams)) *MockusecaseSignInWithGoogle_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.SignInWithGoogleParams))
	})
	return _c
}

func (_c *MockusecaseSignInWithGoogle_Execute_Call) Return(_a0 *usecase.SignInWithGoogleResponse, _a1 error) *MockusecaseSignInWithGoogle_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecaseSignInWithGoogle_Execute_Call) RunAndReturn(run func(context.Context, usecase.SignInWithGoogleParams) (*usecase.SignInWithGoogleResponse, error)) *MockusecaseSignInWithGoogle_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseSignInWithGoogle creates a new instance of MockusecaseSignInWithGoogle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseSignInWithGoogle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseSignInWithGoogle {
	mock := &MockusecaseSignInWithGoogle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
