// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/group/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockusecaseAcceptGroupInvite is an autogenerated mock type for the AcceptGroupInvite type
type MockusecaseAcceptGroupInvite struct {
	mock.Mock
}

type MockusecaseAcceptGroupInvite_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseAcceptGroupInvite) EXPECT() *MockusecaseAcceptGroupInvite_Expecter {
	return &MockusecaseAcceptGroupInvite_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockusecaseAcceptGroupInvite) Execute(ctx context.Context, input usecase.AcceptGroupInviteInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.AcceptGroupInviteInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockusecaseAcceptGroupInvite_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseAcceptGroupInvite_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.AcceptGroupInviteInput
func (_e *MockusecaseAcceptGroupInvite_Expecter) Execute(ctx interface{}, input interface{}) *MockusecaseAcceptGroupInvite_Execute_Call {
	return &MockusecaseAcceptGroupInvite_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockusecaseAcceptGroupInvite_Execute_Call) Run(run func(ctx context.Context, input usecase.AcceptGroupInviteInput)) *MockusecaseAcceptGroupInvite_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.AcceptGroupInviteInput))
	})
	return _c
}

func (_c *MockusecaseAcceptGroupInvite_Execute_Call) Return(_a0 error) *MockusecaseAcceptGroupInvite_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockusecaseAcceptGroupInvite_Execute_Call) RunAndReturn(run func(context.Context, usecase.AcceptGroupInviteInput) error) *MockusecaseAcceptGroupInvite_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseAcceptGroupInvite creates a new instance of MockusecaseAcceptGroupInvite. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseAcceptGroupInvite(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseAcceptGroupInvite {
	mock := &MockusecaseAcceptGroupInvite{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
