// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/auth/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockusecaseSignInWithCredentials is an autogenerated mock type for the SignInWithCredentials type
type MockusecaseSignInWithCredentials struct {
	mock.Mock
}

type MockusecaseSignInWithCredentials_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseSignInWithCredentials) EXPECT() *MockusecaseSignInWithCredentials_Expecter {
	return &MockusecaseSignInWithCredentials_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockusecaseSignInWithCredentials) Execute(ctx context.Context, p usecase.SignInWithCredentialsParams) (*usecase.SignInWithCredentialsResponse, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *usecase.SignInWithCredentialsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.SignInWithCredentialsParams) (*usecase.SignInWithCredentialsResponse, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.SignInWithCredentialsParams) *usecase.SignInWithCredentialsResponse); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.SignInWithCredentialsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.SignInWithCredentialsParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseSignInWithCredentials_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseSignInWithCredentials_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.SignInWithCredentialsParams
func (_e *MockusecaseSignInWithCredentials_Expecter) Execute(ctx interface{}, p interface{}) *MockusecaseSignInWithCredentials_Execute_Call {
	return &MockusecaseSignInWithCredentials_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockusecaseSignInWithCredentials_Execute_Call) Run(run func(ctx context.Context, p usecase.SignInWithCredentialsParams)) *MockusecaseSignInWithCredentials_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.SignInWithCredentialsParams))
	})
	return _c
}

func (_c *MockusecaseSignInWithCredentials_Execute_Call) Return(_a0 *usecase.SignInWithCredentialsResponse, _a1 error) *MockusecaseSignInWithCredentials_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecaseSignInWithCredentials_Execute_Call) RunAndReturn(run func(context.Context, usecase.SignInWithCredentialsParams) (*usecase.SignInWithCredentialsResponse, error)) *MockusecaseSignInWithCredentials_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseSignInWithCredentials creates a new instance of MockusecaseSignInWithCredentials. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseSignInWithCredentials(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseSignInWithCredentials {
	mock := &MockusecaseSignInWithCredentials{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
