// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockpubsubPublisher is an autogenerated mock type for the Publisher type
type MockpubsubPublisher struct {
	mock.Mock
}

type MockpubsubPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockpubsubPublisher) EXPECT() *MockpubsubPublisher_Expecter {
	return &MockpubsubPublisher_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockpubsubPublisher) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockpubsubPublisher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockpubsubPublisher_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockpubsubPublisher_Expecter) Close() *MockpubsubPublisher_Close_Call {
	return &MockpubsubPublisher_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockpubsubPublisher_Close_Call) Run(run func()) *MockpubsubPublisher_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockpubsubPublisher_Close_Call) Return(_a0 error) *MockpubsubPublisher_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockpubsubPublisher_Close_Call) RunAndReturn(run func() error) *MockpubsubPublisher_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, topic, event
func (_m *MockpubsubPublisher) Publish(ctx context.Context, topic string, event interface{}) error {
	ret := _m.Called(ctx, topic, event)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, topic, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockpubsubPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockpubsubPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - event interface{}
func (_e *MockpubsubPublisher_Expecter) Publish(ctx interface{}, topic interface{}, event interface{}) *MockpubsubPublisher_Publish_Call {
	return &MockpubsubPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, topic, event)}
}

func (_c *MockpubsubPublisher_Publish_Call) Run(run func(ctx context.Context, topic string, event interface{})) *MockpubsubPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockpubsubPublisher_Publish_Call) Return(_a0 error) *MockpubsubPublisher_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockpubsubPublisher_Publish_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockpubsubPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockpubsubPublisher creates a new instance of MockpubsubPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockpubsubPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockpubsubPublisher {
	mock := &MockpubsubPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
