// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	expense "github.com/Beigelman/nossas-despesas/internal/modules/expense"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/expense/usecase"
)

// MockusecaseCreateExpense is an autogenerated mock type for the CreateExpense type
type MockusecaseCreateExpense struct {
	mock.Mock
}

type MockusecaseCreateExpense_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseCreateExpense) EXPECT() *MockusecaseCreateExpense_Expecter {
	return &MockusecaseCreateExpense_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockusecaseCreateExpense) Execute(ctx context.Context, p usecase.CreateExpenseParams) (*expense.Expense, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *expense.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateExpenseParams) (*expense.Expense, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateExpenseParams) *expense.Expense); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreateExpenseParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseCreateExpense_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseCreateExpense_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.CreateExpenseParams
func (_e *MockusecaseCreateExpense_Expecter) Execute(ctx interface{}, p interface{}) *MockusecaseCreateExpense_Execute_Call {
	return &MockusecaseCreateExpense_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockusecaseCreateExpense_Execute_Call) Run(run func(ctx context.Context, p usecase.CreateExpenseParams)) *MockusecaseCreateExpense_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateExpenseParams))
	})
	return _c
}

func (_c *MockusecaseCreateExpense_Execute_Call) Return(_a0 *expense.Expense, _a1 error) *MockusecaseCreateExpense_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecaseCreateExpense_Execute_Call) RunAndReturn(run func(context.Context, usecase.CreateExpenseParams) (*expense.Expense, error)) *MockusecaseCreateExpense_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseCreateExpense creates a new instance of MockusecaseCreateExpense. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseCreateExpense(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseCreateExpense {
	mock := &MockusecaseCreateExpense{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
