// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/Beigelman/nossas-despesas/internal/shared/service"
	mock "github.com/stretchr/testify/mock"
)

// MockserviceGoogleTokenValidator is an autogenerated mock type for the GoogleTokenValidator type
type MockserviceGoogleTokenValidator struct {
	mock.Mock
}

type MockserviceGoogleTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockserviceGoogleTokenValidator) EXPECT() *MockserviceGoogleTokenValidator_Expecter {
	return &MockserviceGoogleTokenValidator_Expecter{mock: &_m.Mock}
}

// ValidateToken provides a mock function with given fields: ctx, token
func (_m *MockserviceGoogleTokenValidator) ValidateToken(ctx context.Context, token string) (*service.GoogleTokenClaims, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *service.GoogleTokenClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*service.GoogleTokenClaims, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *service.GoogleTokenClaims); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.GoogleTokenClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockserviceGoogleTokenValidator_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockserviceGoogleTokenValidator_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockserviceGoogleTokenValidator_Expecter) ValidateToken(ctx interface{}, token interface{}) *MockserviceGoogleTokenValidator_ValidateToken_Call {
	return &MockserviceGoogleTokenValidator_ValidateToken_Call{Call: _e.mock.On("ValidateToken", ctx, token)}
}

func (_c *MockserviceGoogleTokenValidator_ValidateToken_Call) Run(run func(ctx context.Context, token string)) *MockserviceGoogleTokenValidator_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockserviceGoogleTokenValidator_ValidateToken_Call) Return(_a0 *service.GoogleTokenClaims, _a1 error) *MockserviceGoogleTokenValidator_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockserviceGoogleTokenValidator_ValidateToken_Call) RunAndReturn(run func(context.Context, string) (*service.GoogleTokenClaims, error)) *MockserviceGoogleTokenValidator_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockserviceGoogleTokenValidator creates a new instance of MockserviceGoogleTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockserviceGoogleTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockserviceGoogleTokenValidator {
	mock := &MockserviceGoogleTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
