// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/expense/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockusecaseCreateScheduledExpense is an autogenerated mock type for the CreateScheduledExpense type
type MockusecaseCreateScheduledExpense struct {
	mock.Mock
}

type MockusecaseCreateScheduledExpense_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseCreateScheduledExpense) EXPECT() *MockusecaseCreateScheduledExpense_Expecter {
	return &MockusecaseCreateScheduledExpense_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockusecaseCreateScheduledExpense) Execute(ctx context.Context, input usecase.CreateScheduledExpenseInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateScheduledExpenseInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockusecaseCreateScheduledExpense_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseCreateScheduledExpense_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.CreateScheduledExpenseInput
func (_e *MockusecaseCreateScheduledExpense_Expecter) Execute(ctx interface{}, input interface{}) *MockusecaseCreateScheduledExpense_Execute_Call {
	return &MockusecaseCreateScheduledExpense_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockusecaseCreateScheduledExpense_Execute_Call) Run(run func(ctx context.Context, input usecase.CreateScheduledExpenseInput)) *MockusecaseCreateScheduledExpense_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateScheduledExpenseInput))
	})
	return _c
}

func (_c *MockusecaseCreateScheduledExpense_Execute_Call) Return(_a0 error) *MockusecaseCreateScheduledExpense_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockusecaseCreateScheduledExpense_Execute_Call) RunAndReturn(run func(context.Context, usecase.CreateScheduledExpenseInput) error) *MockusecaseCreateScheduledExpense_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseCreateScheduledExpense creates a new instance of MockusecaseCreateScheduledExpense. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseCreateScheduledExpense(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseCreateScheduledExpense {
	mock := &MockusecaseCreateScheduledExpense{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
