// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/Beigelman/nossas-despesas/internal/modules/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockauthRepository is an autogenerated mock type for the Repository type
type MockauthRepository struct {
	mock.Mock
}

type MockauthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockauthRepository) EXPECT() *MockauthRepository_Expecter {
	return &MockauthRepository_Expecter{mock: &_m.Mock}
}

// GetByEmail provides a mock function with given fields: ctx, email, authType
func (_m *MockauthRepository) GetByEmail(ctx context.Context, email string, authType auth.Type) (*auth.Auth, error) {
	ret := _m.Called(ctx, email, authType)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *auth.Auth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, auth.Type) (*auth.Auth, error)); ok {
		return rf(ctx, email, authType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, auth.Type) *auth.Auth); ok {
		r0 = rf(ctx, email, authType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Auth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, auth.Type) error); ok {
		r1 = rf(ctx, email, authType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockauthRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockauthRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - authType auth.Type
func (_e *MockauthRepository_Expecter) GetByEmail(ctx interface{}, email interface{}, authType interface{}) *MockauthRepository_GetByEmail_Call {
	return &MockauthRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email, authType)}
}

func (_c *MockauthRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string, authType auth.Type)) *MockauthRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(auth.Type))
	})
	return _c
}

func (_c *MockauthRepository_GetByEmail_Call) Return(_a0 *auth.Auth, _a1 error) *MockauthRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockauthRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string, auth.Type) (*auth.Auth, error)) *MockauthRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockauthRepository) GetByID(ctx context.Context, id auth.ID) (*auth.Auth, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *auth.Auth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.ID) (*auth.Auth, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.ID) *auth.Auth); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Auth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockauthRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockauthRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id auth.ID
func (_e *MockauthRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockauthRepository_GetByID_Call {
	return &MockauthRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockauthRepository_GetByID_Call) Run(run func(ctx context.Context, id auth.ID)) *MockauthRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.ID))
	})
	return _c
}

func (_c *MockauthRepository_GetByID_Call) Return(_a0 *auth.Auth, _a1 error) *MockauthRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockauthRepository_GetByID_Call) RunAndReturn(run func(context.Context, auth.ID) (*auth.Auth, error)) *MockauthRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with no fields
func (_m *MockauthRepository) GetNextID() auth.ID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNextID")
	}

	var r0 auth.ID
	if rf, ok := ret.Get(0).(func() auth.ID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(auth.ID)
	}

	return r0
}

// MockauthRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockauthRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockauthRepository_Expecter) GetNextID() *MockauthRepository_GetNextID_Call {
	return &MockauthRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockauthRepository_GetNextID_Call) Run(run func()) *MockauthRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockauthRepository_GetNextID_Call) Return(_a0 auth.ID) *MockauthRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockauthRepository_GetNextID_Call) RunAndReturn(run func() auth.ID) *MockauthRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, entity
func (_m *MockauthRepository) Store(ctx context.Context, entity *auth.Auth) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.Auth) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockauthRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockauthRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *auth.Auth
func (_e *MockauthRepository_Expecter) Store(ctx interface{}, entity interface{}) *MockauthRepository_Store_Call {
	return &MockauthRepository_Store_Call{Call: _e.mock.On("Store", ctx, entity)}
}

func (_c *MockauthRepository_Store_Call) Run(run func(ctx context.Context, entity *auth.Auth)) *MockauthRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.Auth))
	})
	return _c
}

func (_c *MockauthRepository_Store_Call) Return(_a0 error) *MockauthRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockauthRepository_Store_Call) RunAndReturn(run func(context.Context, *auth.Auth) error) *MockauthRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockauthRepository creates a new instance of MockauthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockauthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockauthRepository {
	mock := &MockauthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
