// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	category "github.com/Beigelman/nossas-despesas/internal/modules/category"

	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/category/usecase"
)

// MockusecaseCreateCategoryGroup is an autogenerated mock type for the CreateCategoryGroup type
type MockusecaseCreateCategoryGroup struct {
	mock.Mock
}

type MockusecaseCreateCategoryGroup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseCreateCategoryGroup) EXPECT() *MockusecaseCreateCategoryGroup_Expecter {
	return &MockusecaseCreateCategoryGroup_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockusecaseCreateCategoryGroup) Execute(ctx context.Context, input usecase.CreateCategoryGroupInput) (*category.Group, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *category.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateCategoryGroupInput) (*category.Group, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateCategoryGroupInput) *category.Group); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreateCategoryGroupInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseCreateCategoryGroup_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseCreateCategoryGroup_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.CreateCategoryGroupInput
func (_e *MockusecaseCreateCategoryGroup_Expecter) Execute(ctx interface{}, input interface{}) *MockusecaseCreateCategoryGroup_Execute_Call {
	return &MockusecaseCreateCategoryGroup_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockusecaseCreateCategoryGroup_Execute_Call) Run(run func(ctx context.Context, input usecase.CreateCategoryGroupInput)) *MockusecaseCreateCategoryGroup_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateCategoryGroupInput))
	})
	return _c
}

func (_c *MockusecaseCreateCategoryGroup_Execute_Call) Return(_a0 *category.Group, _a1 error) *MockusecaseCreateCategoryGroup_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecaseCreateCategoryGroup_Execute_Call) RunAndReturn(run func(context.Context, usecase.CreateCategoryGroupInput) (*category.Group, error)) *MockusecaseCreateCategoryGroup_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseCreateCategoryGroup creates a new instance of MockusecaseCreateCategoryGroup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseCreateCategoryGroup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseCreateCategoryGroup {
	mock := &MockusecaseCreateCategoryGroup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
