// Code generated by mockery v2.23.4. DO NOT EDIT.

package mockrepository

import (
	context "context"

	entity "github.com/Beigelman/ludaapi/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockGroupCategoryRepository is an autogenerated mock type for the GroupCategoryRepository type
type MockGroupCategoryRepository struct {
	mock.Mock
}

type MockGroupCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupCategoryRepository) EXPECT() *MockGroupCategoryRepository_Expecter {
	return &MockGroupCategoryRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockGroupCategoryRepository) GetByID(ctx context.Context, id entity.CategoryGroupID) (*entity.CategoryGroup, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.CategoryGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CategoryGroupID) (*entity.CategoryGroup, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CategoryGroupID) *entity.CategoryGroup); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CategoryGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CategoryGroupID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupCategoryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockGroupCategoryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.CategoryGroupID
func (_e *MockGroupCategoryRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockGroupCategoryRepository_GetByID_Call {
	return &MockGroupCategoryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockGroupCategoryRepository_GetByID_Call) Run(run func(ctx context.Context, id entity.CategoryGroupID)) *MockGroupCategoryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CategoryGroupID))
	})
	return _c
}

func (_c *MockGroupCategoryRepository_GetByID_Call) Return(_a0 *entity.CategoryGroup, _a1 error) *MockGroupCategoryRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupCategoryRepository_GetByID_Call) RunAndReturn(run func(context.Context, entity.CategoryGroupID) (*entity.CategoryGroup, error)) *MockGroupCategoryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockGroupCategoryRepository) GetByName(ctx context.Context, name string) (*entity.CategoryGroup, error) {
	ret := _m.Called(ctx, name)

	var r0 *entity.CategoryGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.CategoryGroup, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.CategoryGroup); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CategoryGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupCategoryRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockGroupCategoryRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockGroupCategoryRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockGroupCategoryRepository_GetByName_Call {
	return &MockGroupCategoryRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockGroupCategoryRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockGroupCategoryRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGroupCategoryRepository_GetByName_Call) Return(_a0 *entity.CategoryGroup, _a1 error) *MockGroupCategoryRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupCategoryRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*entity.CategoryGroup, error)) *MockGroupCategoryRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockGroupCategoryRepository) GetNextID() entity.CategoryGroupID {
	ret := _m.Called()

	var r0 entity.CategoryGroupID
	if rf, ok := ret.Get(0).(func() entity.CategoryGroupID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entity.CategoryGroupID)
	}

	return r0
}

// MockGroupCategoryRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockGroupCategoryRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockGroupCategoryRepository_Expecter) GetNextID() *MockGroupCategoryRepository_GetNextID_Call {
	return &MockGroupCategoryRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockGroupCategoryRepository_GetNextID_Call) Run(run func()) *MockGroupCategoryRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGroupCategoryRepository_GetNextID_Call) Return(_a0 entity.CategoryGroupID) *MockGroupCategoryRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupCategoryRepository_GetNextID_Call) RunAndReturn(run func() entity.CategoryGroupID) *MockGroupCategoryRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, _a1
func (_m *MockGroupCategoryRepository) Store(ctx context.Context, _a1 *entity.CategoryGroup) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.CategoryGroup) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupCategoryRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockGroupCategoryRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.CategoryGroup
func (_e *MockGroupCategoryRepository_Expecter) Store(ctx interface{}, _a1 interface{}) *MockGroupCategoryRepository_Store_Call {
	return &MockGroupCategoryRepository_Store_Call{Call: _e.mock.On("Store", ctx, _a1)}
}

func (_c *MockGroupCategoryRepository_Store_Call) Run(run func(ctx context.Context, _a1 *entity.CategoryGroup)) *MockGroupCategoryRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.CategoryGroup))
	})
	return _c
}

func (_c *MockGroupCategoryRepository_Store_Call) Return(_a0 error) *MockGroupCategoryRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupCategoryRepository_Store_Call) RunAndReturn(run func(context.Context, *entity.CategoryGroup) error) *MockGroupCategoryRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupCategoryRepository creates a new instance of MockGroupCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupCategoryRepository {
	mock := &MockGroupCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
