// Code generated by mockery v2.35.2. DO NOT EDIT.

package mockrepository

import (
	context "context"

	entity "github.com/Beigelman/nossas-despesas/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*entity.User, error) {
	ret := _m.Called(ctx, email)

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockUserRepository_GetByEmail_Call {
	return &MockUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) Return(_a0 *entity.User, _a1 error) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*entity.User, error)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) GetByID(ctx context.Context, id entity.UserID) (*entity.User, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserID) (*entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserID) *entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UserID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.UserID
func (_e *MockUserRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserRepository_GetByID_Call {
	return &MockUserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserRepository_GetByID_Call) Run(run func(ctx context.Context, id entity.UserID)) *MockUserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.UserID))
	})
	return _c
}

func (_c *MockUserRepository_GetByID_Call) Return(_a0 *entity.User, _a1 error) *MockUserRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetByID_Call) RunAndReturn(run func(context.Context, entity.UserID) (*entity.User, error)) *MockUserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockUserRepository) GetNextID() entity.UserID {
	ret := _m.Called()

	var r0 entity.UserID
	if rf, ok := ret.Get(0).(func() entity.UserID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entity.UserID)
	}

	return r0
}

// MockUserRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockUserRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockUserRepository_Expecter) GetNextID() *MockUserRepository_GetNextID_Call {
	return &MockUserRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockUserRepository_GetNextID_Call) Run(run func()) *MockUserRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserRepository_GetNextID_Call) Return(_a0 entity.UserID) *MockUserRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_GetNextID_Call) RunAndReturn(run func() entity.UserID) *MockUserRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, _a1
func (_m *MockUserRepository) Store(ctx context.Context, _a1 *entity.User) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockUserRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.User
func (_e *MockUserRepository_Expecter) Store(ctx interface{}, _a1 interface{}) *MockUserRepository_Store_Call {
	return &MockUserRepository_Store_Call{Call: _e.mock.On("Store", ctx, _a1)}
}

func (_c *MockUserRepository_Store_Call) Run(run func(ctx context.Context, _a1 *entity.User)) *MockUserRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.User))
	})
	return _c
}

func (_c *MockUserRepository_Store_Call) Return(_a0 error) *MockUserRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Store_Call) RunAndReturn(run func(context.Context, *entity.User) error) *MockUserRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
