// Code generated by mockery v2.43.2. DO NOT EDIT.

package mockrepository

import (
	context "context"
	entity "github.com/Beigelman/nossas-despesas/internal/modules/expense"
	"github.com/Beigelman/nossas-despesas/internal/modules/group"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockExpenseRepository is an autogenerated mock type for the Repository type
type MockExpenseRepository struct {
	mock.Mock
}

type MockExpenseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpenseRepository) EXPECT() *MockExpenseRepository_Expecter {
	return &MockExpenseRepository_Expecter{mock: &_m.Mock}
}

// BulkStore provides a mock function with given fields: ctx, expenses
func (_m *MockExpenseRepository) BulkStore(ctx context.Context, expenses []entity.Expense) error {
	ret := _m.Called(ctx, expenses)

	if len(ret) == 0 {
		panic("no return value specified for BulkStore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.Expense) error); ok {
		r0 = rf(ctx, expenses)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseRepository_BulkStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkStore'
type MockExpenseRepository_BulkStore_Call struct {
	*mock.Call
}

// BulkStore is a helper method to define mock.On call
//   - ctx context.Context
//   - expenses []entity.Expense
func (_e *MockExpenseRepository_Expecter) BulkStore(ctx interface{}, expenses interface{}) *MockExpenseRepository_BulkStore_Call {
	return &MockExpenseRepository_BulkStore_Call{Call: _e.mock.On("BulkStore", ctx, expenses)}
}

func (_c *MockExpenseRepository_BulkStore_Call) Run(run func(ctx context.Context, expenses []entity.Expense)) *MockExpenseRepository_BulkStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.Expense))
	})
	return _c
}

func (_c *MockExpenseRepository_BulkStore_Call) Return(_a0 error) *MockExpenseRepository_BulkStore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseRepository_BulkStore_Call) RunAndReturn(run func(context.Context, []entity.Expense) error) *MockExpenseRepository_BulkStore_Call {
	_c.Call.Return(run)
	return _c
}

// GetByGroupDate provides a mock function with given fields: ctx, groupId, date
func (_m *MockExpenseRepository) GetByGroupDate(ctx context.Context, groupId group.ID, date time.Time) ([]entity.Expense, error) {
	ret := _m.Called(ctx, groupId, date)

	if len(ret) == 0 {
		panic("no return value specified for GetByGroupDate")
	}

	var r0 []entity.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, group.ID, time.Time) ([]entity.Expense, error)); ok {
		return rf(ctx, groupId, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, group.ID, time.Time) []entity.Expense); ok {
		r0 = rf(ctx, groupId, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, group.ID, time.Time) error); ok {
		r1 = rf(ctx, groupId, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpenseRepository_GetByGroupDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByGroupDate'
type MockExpenseRepository_GetByGroupDate_Call struct {
	*mock.Call
}

// GetByGroupDate is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId entity.ID
//   - date time.Time
func (_e *MockExpenseRepository_Expecter) GetByGroupDate(ctx interface{}, groupId interface{}, date interface{}) *MockExpenseRepository_GetByGroupDate_Call {
	return &MockExpenseRepository_GetByGroupDate_Call{Call: _e.mock.On("GetByGroupDate", ctx, groupId, date)}
}

func (_c *MockExpenseRepository_GetByGroupDate_Call) Run(run func(ctx context.Context, groupId group.ID, date time.Time)) *MockExpenseRepository_GetByGroupDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(group.ID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockExpenseRepository_GetByGroupDate_Call) Return(_a0 []entity.Expense, _a1 error) *MockExpenseRepository_GetByGroupDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpenseRepository_GetByGroupDate_Call) RunAndReturn(run func(context.Context, group.ID, time.Time) ([]entity.Expense, error)) *MockExpenseRepository_GetByGroupDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockExpenseRepository) GetByID(ctx context.Context, id entity.ID) (*entity.Expense, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ID) (*entity.Expense, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ID) *entity.Expense); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpenseRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockExpenseRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.ID
func (_e *MockExpenseRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockExpenseRepository_GetByID_Call {
	return &MockExpenseRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockExpenseRepository_GetByID_Call) Run(run func(ctx context.Context, id entity.ID)) *MockExpenseRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ID))
	})
	return _c
}

func (_c *MockExpenseRepository_GetByID_Call) Return(_a0 *entity.Expense, _a1 error) *MockExpenseRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpenseRepository_GetByID_Call) RunAndReturn(run func(context.Context, entity.ID) (*entity.Expense, error)) *MockExpenseRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockExpenseRepository) GetNextID() entity.ID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNextID")
	}

	var r0 entity.ID
	if rf, ok := ret.Get(0).(func() entity.ID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entity.ID)
	}

	return r0
}

// MockExpenseRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockExpenseRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockExpenseRepository_Expecter) GetNextID() *MockExpenseRepository_GetNextID_Call {
	return &MockExpenseRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockExpenseRepository_GetNextID_Call) Run(run func()) *MockExpenseRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExpenseRepository_GetNextID_Call) Return(_a0 entity.ID) *MockExpenseRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseRepository_GetNextID_Call) RunAndReturn(run func() entity.ID) *MockExpenseRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, _a1
func (_m *MockExpenseRepository) Store(ctx context.Context, _a1 *entity.Expense) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Expense) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockExpenseRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Expense
func (_e *MockExpenseRepository_Expecter) Store(ctx interface{}, _a1 interface{}) *MockExpenseRepository_Store_Call {
	return &MockExpenseRepository_Store_Call{Call: _e.mock.On("Store", ctx, _a1)}
}

func (_c *MockExpenseRepository_Store_Call) Run(run func(ctx context.Context, _a1 *entity.Expense)) *MockExpenseRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Expense))
	})
	return _c
}

func (_c *MockExpenseRepository_Store_Call) Return(_a0 error) *MockExpenseRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseRepository_Store_Call) RunAndReturn(run func(context.Context, *entity.Expense) error) *MockExpenseRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExpenseRepository creates a new instance of MockExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpenseRepository {
	mock := &MockExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
