// Code generated by mockery v2.23.4. DO NOT EDIT.

package mockrepository

import (
	context "context"

	entity "github.com/Beigelman/nossas-despesas/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockGroupInviteRepository is an autogenerated mock type for the GroupInviteRepository type
type MockGroupInviteRepository struct {
	mock.Mock
}

type MockGroupInviteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupInviteRepository) EXPECT() *MockGroupInviteRepository_Expecter {
	return &MockGroupInviteRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockGroupInviteRepository) GetByID(ctx context.Context, id entity.GroupInviteID) (*entity.GroupInvite, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.GroupInvite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.GroupInviteID) (*entity.GroupInvite, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.GroupInviteID) *entity.GroupInvite); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.GroupInvite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.GroupInviteID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupInviteRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockGroupInviteRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.GroupInviteID
func (_e *MockGroupInviteRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockGroupInviteRepository_GetByID_Call {
	return &MockGroupInviteRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockGroupInviteRepository_GetByID_Call) Run(run func(ctx context.Context, id entity.GroupInviteID)) *MockGroupInviteRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.GroupInviteID))
	})
	return _c
}

func (_c *MockGroupInviteRepository_GetByID_Call) Return(_a0 *entity.GroupInvite, _a1 error) *MockGroupInviteRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupInviteRepository_GetByID_Call) RunAndReturn(run func(context.Context, entity.GroupInviteID) (*entity.GroupInvite, error)) *MockGroupInviteRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByToken provides a mock function with given fields: ctx, token
func (_m *MockGroupInviteRepository) GetByToken(ctx context.Context, token string) (*entity.GroupInvite, error) {
	ret := _m.Called(ctx, token)

	var r0 *entity.GroupInvite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.GroupInvite, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.GroupInvite); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.GroupInvite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupInviteRepository_GetByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByToken'
type MockGroupInviteRepository_GetByToken_Call struct {
	*mock.Call
}

// GetByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockGroupInviteRepository_Expecter) GetByToken(ctx interface{}, token interface{}) *MockGroupInviteRepository_GetByToken_Call {
	return &MockGroupInviteRepository_GetByToken_Call{Call: _e.mock.On("GetByToken", ctx, token)}
}

func (_c *MockGroupInviteRepository_GetByToken_Call) Run(run func(ctx context.Context, token string)) *MockGroupInviteRepository_GetByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGroupInviteRepository_GetByToken_Call) Return(_a0 *entity.GroupInvite, _a1 error) *MockGroupInviteRepository_GetByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupInviteRepository_GetByToken_Call) RunAndReturn(run func(context.Context, string) (*entity.GroupInvite, error)) *MockGroupInviteRepository_GetByToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupInvitesByEmail provides a mock function with given fields: ctx, groupID, email
func (_m *MockGroupInviteRepository) GetGroupInvitesByEmail(ctx context.Context, groupID entity.GroupID, email string) ([]entity.GroupInvite, error) {
	ret := _m.Called(ctx, groupID, email)

	var r0 []entity.GroupInvite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.GroupID, string) ([]entity.GroupInvite, error)); ok {
		return rf(ctx, groupID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.GroupID, string) []entity.GroupInvite); ok {
		r0 = rf(ctx, groupID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.GroupInvite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.GroupID, string) error); ok {
		r1 = rf(ctx, groupID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupInviteRepository_GetGroupInvitesByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupInvitesByEmail'
type MockGroupInviteRepository_GetGroupInvitesByEmail_Call struct {
	*mock.Call
}

// GetGroupInvitesByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID entity.GroupID
//   - email string
func (_e *MockGroupInviteRepository_Expecter) GetGroupInvitesByEmail(ctx interface{}, groupID interface{}, email interface{}) *MockGroupInviteRepository_GetGroupInvitesByEmail_Call {
	return &MockGroupInviteRepository_GetGroupInvitesByEmail_Call{Call: _e.mock.On("GetGroupInvitesByEmail", ctx, groupID, email)}
}

func (_c *MockGroupInviteRepository_GetGroupInvitesByEmail_Call) Run(run func(ctx context.Context, groupID entity.GroupID, email string)) *MockGroupInviteRepository_GetGroupInvitesByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.GroupID), args[2].(string))
	})
	return _c
}

func (_c *MockGroupInviteRepository_GetGroupInvitesByEmail_Call) Return(_a0 []entity.GroupInvite, _a1 error) *MockGroupInviteRepository_GetGroupInvitesByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupInviteRepository_GetGroupInvitesByEmail_Call) RunAndReturn(run func(context.Context, entity.GroupID, string) ([]entity.GroupInvite, error)) *MockGroupInviteRepository_GetGroupInvitesByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockGroupInviteRepository) GetNextID() entity.GroupInviteID {
	ret := _m.Called()

	var r0 entity.GroupInviteID
	if rf, ok := ret.Get(0).(func() entity.GroupInviteID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entity.GroupInviteID)
	}

	return r0
}

// MockGroupInviteRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockGroupInviteRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockGroupInviteRepository_Expecter) GetNextID() *MockGroupInviteRepository_GetNextID_Call {
	return &MockGroupInviteRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockGroupInviteRepository_GetNextID_Call) Run(run func()) *MockGroupInviteRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGroupInviteRepository_GetNextID_Call) Return(_a0 entity.GroupInviteID) *MockGroupInviteRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupInviteRepository_GetNextID_Call) RunAndReturn(run func() entity.GroupInviteID) *MockGroupInviteRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, _a1
func (_m *MockGroupInviteRepository) Store(ctx context.Context, _a1 *entity.GroupInvite) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.GroupInvite) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupInviteRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockGroupInviteRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.GroupInvite
func (_e *MockGroupInviteRepository_Expecter) Store(ctx interface{}, _a1 interface{}) *MockGroupInviteRepository_Store_Call {
	return &MockGroupInviteRepository_Store_Call{Call: _e.mock.On("Store", ctx, _a1)}
}

func (_c *MockGroupInviteRepository_Store_Call) Run(run func(ctx context.Context, _a1 *entity.GroupInvite)) *MockGroupInviteRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.GroupInvite))
	})
	return _c
}

func (_c *MockGroupInviteRepository_Store_Call) Return(_a0 error) *MockGroupInviteRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupInviteRepository_Store_Call) RunAndReturn(run func(context.Context, *entity.GroupInvite) error) *MockGroupInviteRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupInviteRepository creates a new instance of MockGroupInviteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupInviteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupInviteRepository {
	mock := &MockGroupInviteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
