// Code generated by mockery v2.23.4. DO NOT EDIT.

package mockrepository

import (
	context "context"

	entity "github.com/Beigelman/nossas-despesas/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockCategoryRepository is an autogenerated mock type for the CategoryRepository type
type MockCategoryRepository struct {
	mock.Mock
}

type MockCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryRepository) EXPECT() *MockCategoryRepository_Expecter {
	return &MockCategoryRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockCategoryRepository) GetByID(ctx context.Context, id entity.CategoryID) (*entity.Category, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CategoryID) (*entity.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CategoryID) *entity.Category); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CategoryID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCategoryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.CategoryID
func (_e *MockCategoryRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockCategoryRepository_GetByID_Call {
	return &MockCategoryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCategoryRepository_GetByID_Call) Run(run func(ctx context.Context, id entity.CategoryID)) *MockCategoryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CategoryID))
	})
	return _c
}

func (_c *MockCategoryRepository_GetByID_Call) Return(_a0 *entity.Category, _a1 error) *MockCategoryRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_GetByID_Call) RunAndReturn(run func(context.Context, entity.CategoryID) (*entity.Category, error)) *MockCategoryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockCategoryRepository) GetByName(ctx context.Context, name string) (*entity.Category, error) {
	ret := _m.Called(ctx, name)

	var r0 *entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Category, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Category); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockCategoryRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCategoryRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockCategoryRepository_GetByName_Call {
	return &MockCategoryRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockCategoryRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockCategoryRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCategoryRepository_GetByName_Call) Return(_a0 *entity.Category, _a1 error) *MockCategoryRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*entity.Category, error)) *MockCategoryRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockCategoryRepository) GetNextID() entity.CategoryID {
	ret := _m.Called()

	var r0 entity.CategoryID
	if rf, ok := ret.Get(0).(func() entity.CategoryID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entity.CategoryID)
	}

	return r0
}

// MockCategoryRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockCategoryRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockCategoryRepository_Expecter) GetNextID() *MockCategoryRepository_GetNextID_Call {
	return &MockCategoryRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockCategoryRepository_GetNextID_Call) Run(run func()) *MockCategoryRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCategoryRepository_GetNextID_Call) Return(_a0 entity.CategoryID) *MockCategoryRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryRepository_GetNextID_Call) RunAndReturn(run func() entity.CategoryID) *MockCategoryRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, _a1
func (_m *MockCategoryRepository) Store(ctx context.Context, _a1 *entity.Category) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Category) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockCategoryRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Category
func (_e *MockCategoryRepository_Expecter) Store(ctx interface{}, _a1 interface{}) *MockCategoryRepository_Store_Call {
	return &MockCategoryRepository_Store_Call{Call: _e.mock.On("Store", ctx, _a1)}
}

func (_c *MockCategoryRepository_Store_Call) Run(run func(ctx context.Context, _a1 *entity.Category)) *MockCategoryRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Category))
	})
	return _c
}

func (_c *MockCategoryRepository_Store_Call) Return(_a0 error) *MockCategoryRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryRepository_Store_Call) RunAndReturn(run func(context.Context, *entity.Category) error) *MockCategoryRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryRepository creates a new instance of MockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepository {
	mock := &MockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
