// Code generated by mockery v2.23.4. DO NOT EDIT.

package mockrepository

import (
	context "context"

	entity "github.com/Beigelman/nossas-despesas/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

type MockAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepository) EXPECT() *MockAuthRepository_Expecter {
	return &MockAuthRepository_Expecter{mock: &_m.Mock}
}

// GetByEmail provides a mock function with given fields: ctx, email, authType
func (_m *MockAuthRepository) GetByEmail(ctx context.Context, email string, authType entity.AuthType) (*entity.Auth, error) {
	ret := _m.Called(ctx, email, authType)

	var r0 *entity.Auth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.AuthType) (*entity.Auth, error)); ok {
		return rf(ctx, email, authType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.AuthType) *entity.Auth); ok {
		r0 = rf(ctx, email, authType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Auth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entity.AuthType) error); ok {
		r1 = rf(ctx, email, authType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockAuthRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - authType entity.AuthType
func (_e *MockAuthRepository_Expecter) GetByEmail(ctx interface{}, email interface{}, authType interface{}) *MockAuthRepository_GetByEmail_Call {
	return &MockAuthRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email, authType)}
}

func (_c *MockAuthRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string, authType entity.AuthType)) *MockAuthRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entity.AuthType))
	})
	return _c
}

func (_c *MockAuthRepository_GetByEmail_Call) Return(_a0 *entity.Auth, _a1 error) *MockAuthRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string, entity.AuthType) (*entity.Auth, error)) *MockAuthRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockAuthRepository) GetByID(ctx context.Context, id entity.AuthID) (*entity.Auth, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.Auth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.AuthID) (*entity.Auth, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.AuthID) *entity.Auth); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Auth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.AuthID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAuthRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.AuthID
func (_e *MockAuthRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockAuthRepository_GetByID_Call {
	return &MockAuthRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAuthRepository_GetByID_Call) Run(run func(ctx context.Context, id entity.AuthID)) *MockAuthRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.AuthID))
	})
	return _c
}

func (_c *MockAuthRepository_GetByID_Call) Return(_a0 *entity.Auth, _a1 error) *MockAuthRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthRepository_GetByID_Call) RunAndReturn(run func(context.Context, entity.AuthID) (*entity.Auth, error)) *MockAuthRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockAuthRepository) GetNextID() entity.AuthID {
	ret := _m.Called()

	var r0 entity.AuthID
	if rf, ok := ret.Get(0).(func() entity.AuthID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entity.AuthID)
	}

	return r0
}

// MockAuthRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockAuthRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockAuthRepository_Expecter) GetNextID() *MockAuthRepository_GetNextID_Call {
	return &MockAuthRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockAuthRepository_GetNextID_Call) Run(run func()) *MockAuthRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthRepository_GetNextID_Call) Return(_a0 entity.AuthID) *MockAuthRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthRepository_GetNextID_Call) RunAndReturn(run func() entity.AuthID) *MockAuthRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, _a1
func (_m *MockAuthRepository) Store(ctx context.Context, _a1 *entity.Auth) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Auth) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockAuthRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Auth
func (_e *MockAuthRepository_Expecter) Store(ctx interface{}, _a1 interface{}) *MockAuthRepository_Store_Call {
	return &MockAuthRepository_Store_Call{Call: _e.mock.On("Store", ctx, _a1)}
}

func (_c *MockAuthRepository_Store_Call) Run(run func(ctx context.Context, _a1 *entity.Auth)) *MockAuthRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Auth))
	})
	return _c
}

func (_c *MockAuthRepository_Store_Call) Return(_a0 error) *MockAuthRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthRepository_Store_Call) RunAndReturn(run func(context.Context, *entity.Auth) error) *MockAuthRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
