// Code generated by mockery v2.23.4. DO NOT EDIT.

package mockrepository

import (
	context "context"

	entity "github.com/Beigelman/ludaapi/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockIncomeRepository is an autogenerated mock type for the IncomeRepository type
type MockIncomeRepository struct {
	mock.Mock
}

type MockIncomeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncomeRepository) EXPECT() *MockIncomeRepository_Expecter {
	return &MockIncomeRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockIncomeRepository) GetByID(ctx context.Context, id entity.IncomeID) (*entity.Income, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.Income
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.IncomeID) (*entity.Income, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.IncomeID) *entity.Income); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Income)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.IncomeID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIncomeRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIncomeRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.IncomeID
func (_e *MockIncomeRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockIncomeRepository_GetByID_Call {
	return &MockIncomeRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIncomeRepository_GetByID_Call) Run(run func(ctx context.Context, id entity.IncomeID)) *MockIncomeRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.IncomeID))
	})
	return _c
}

func (_c *MockIncomeRepository_GetByID_Call) Return(_a0 *entity.Income, _a1 error) *MockIncomeRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIncomeRepository_GetByID_Call) RunAndReturn(run func(context.Context, entity.IncomeID) (*entity.Income, error)) *MockIncomeRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockIncomeRepository) GetNextID() entity.IncomeID {
	ret := _m.Called()

	var r0 entity.IncomeID
	if rf, ok := ret.Get(0).(func() entity.IncomeID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entity.IncomeID)
	}

	return r0
}

// MockIncomeRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockIncomeRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockIncomeRepository_Expecter) GetNextID() *MockIncomeRepository_GetNextID_Call {
	return &MockIncomeRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockIncomeRepository_GetNextID_Call) Run(run func()) *MockIncomeRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomeRepository_GetNextID_Call) Return(_a0 entity.IncomeID) *MockIncomeRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncomeRepository_GetNextID_Call) RunAndReturn(run func() entity.IncomeID) *MockIncomeRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserMonthlyIncomes provides a mock function with given fields: ctx, userID, date
func (_m *MockIncomeRepository) GetUserMonthlyIncomes(ctx context.Context, userID entity.UserID, date *time.Time) ([]entity.Income, error) {
	ret := _m.Called(ctx, userID, date)

	var r0 []entity.Income
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserID, *time.Time) ([]entity.Income, error)); ok {
		return rf(ctx, userID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserID, *time.Time) []entity.Income); ok {
		r0 = rf(ctx, userID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Income)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UserID, *time.Time) error); ok {
		r1 = rf(ctx, userID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIncomeRepository_GetUserMonthlyIncomes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserMonthlyIncomes'
type MockIncomeRepository_GetUserMonthlyIncomes_Call struct {
	*mock.Call
}

// GetUserMonthlyIncomes is a helper method to define mock.On call
//   - ctx context.Context
//   - userID entity.UserID
//   - date *time.Time
func (_e *MockIncomeRepository_Expecter) GetUserMonthlyIncomes(ctx interface{}, userID interface{}, date interface{}) *MockIncomeRepository_GetUserMonthlyIncomes_Call {
	return &MockIncomeRepository_GetUserMonthlyIncomes_Call{Call: _e.mock.On("GetUserMonthlyIncomes", ctx, userID, date)}
}

func (_c *MockIncomeRepository_GetUserMonthlyIncomes_Call) Run(run func(ctx context.Context, userID entity.UserID, date *time.Time)) *MockIncomeRepository_GetUserMonthlyIncomes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.UserID), args[2].(*time.Time))
	})
	return _c
}

func (_c *MockIncomeRepository_GetUserMonthlyIncomes_Call) Return(_a0 []entity.Income, _a1 error) *MockIncomeRepository_GetUserMonthlyIncomes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIncomeRepository_GetUserMonthlyIncomes_Call) RunAndReturn(run func(context.Context, entity.UserID, *time.Time) ([]entity.Income, error)) *MockIncomeRepository_GetUserMonthlyIncomes_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, _a1
func (_m *MockIncomeRepository) Store(ctx context.Context, _a1 *entity.Income) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Income) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncomeRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockIncomeRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Income
func (_e *MockIncomeRepository_Expecter) Store(ctx interface{}, _a1 interface{}) *MockIncomeRepository_Store_Call {
	return &MockIncomeRepository_Store_Call{Call: _e.mock.On("Store", ctx, _a1)}
}

func (_c *MockIncomeRepository_Store_Call) Run(run func(ctx context.Context, _a1 *entity.Income)) *MockIncomeRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Income))
	})
	return _c
}

func (_c *MockIncomeRepository_Store_Call) Return(_a0 error) *MockIncomeRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncomeRepository_Store_Call) RunAndReturn(run func(context.Context, *entity.Income) error) *MockIncomeRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIncomeRepository creates a new instance of MockIncomeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncomeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncomeRepository {
	mock := &MockIncomeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
