// Code generated by mockery v2.43.2. DO NOT EDIT.

package mockrepository

import (
	context "context"
	entity "github.com/Beigelman/nossas-despesas/internal/modules/category"

	mock "github.com/stretchr/testify/mock"
)

// MockCategoryGroupRepository is an autogenerated mock type for the GroupRepository type
type MockCategoryGroupRepository struct {
	mock.Mock
}

type MockCategoryGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryGroupRepository) EXPECT() *MockCategoryGroupRepository_Expecter {
	return &MockCategoryGroupRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockCategoryGroupRepository) GetByID(ctx context.Context, id entity.GroupID) (*entity.Group, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.GroupID) (*entity.Group, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.GroupID) *entity.Group); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.GroupID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryGroupRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCategoryGroupRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.GroupID
func (_e *MockCategoryGroupRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockCategoryGroupRepository_GetByID_Call {
	return &MockCategoryGroupRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCategoryGroupRepository_GetByID_Call) Run(run func(ctx context.Context, id entity.GroupID)) *MockCategoryGroupRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.GroupID))
	})
	return _c
}

func (_c *MockCategoryGroupRepository_GetByID_Call) Return(_a0 *entity.Group, _a1 error) *MockCategoryGroupRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryGroupRepository_GetByID_Call) RunAndReturn(run func(context.Context, entity.GroupID) (*entity.Group, error)) *MockCategoryGroupRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockCategoryGroupRepository) GetByName(ctx context.Context, name string) (*entity.Group, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *entity.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Group, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Group); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryGroupRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockCategoryGroupRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCategoryGroupRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockCategoryGroupRepository_GetByName_Call {
	return &MockCategoryGroupRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockCategoryGroupRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockCategoryGroupRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCategoryGroupRepository_GetByName_Call) Return(_a0 *entity.Group, _a1 error) *MockCategoryGroupRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryGroupRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*entity.Group, error)) *MockCategoryGroupRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockCategoryGroupRepository) GetNextID() entity.GroupID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNextID")
	}

	var r0 entity.GroupID
	if rf, ok := ret.Get(0).(func() entity.GroupID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entity.GroupID)
	}

	return r0
}

// MockCategoryGroupRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockCategoryGroupRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockCategoryGroupRepository_Expecter) GetNextID() *MockCategoryGroupRepository_GetNextID_Call {
	return &MockCategoryGroupRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockCategoryGroupRepository_GetNextID_Call) Run(run func()) *MockCategoryGroupRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCategoryGroupRepository_GetNextID_Call) Return(_a0 entity.GroupID) *MockCategoryGroupRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryGroupRepository_GetNextID_Call) RunAndReturn(run func() entity.GroupID) *MockCategoryGroupRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, _a1
func (_m *MockCategoryGroupRepository) Store(ctx context.Context, _a1 *entity.Group) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Group) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryGroupRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockCategoryGroupRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Group
func (_e *MockCategoryGroupRepository_Expecter) Store(ctx interface{}, _a1 interface{}) *MockCategoryGroupRepository_Store_Call {
	return &MockCategoryGroupRepository_Store_Call{Call: _e.mock.On("Store", ctx, _a1)}
}

func (_c *MockCategoryGroupRepository_Store_Call) Run(run func(ctx context.Context, _a1 *entity.Group)) *MockCategoryGroupRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Group))
	})
	return _c
}

func (_c *MockCategoryGroupRepository_Store_Call) Return(_a0 error) *MockCategoryGroupRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryGroupRepository_Store_Call) RunAndReturn(run func(context.Context, *entity.Group) error) *MockCategoryGroupRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryGroupRepository creates a new instance of MockCategoryGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryGroupRepository {
	mock := &MockCategoryGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
