// Code generated by mockery v2.23.4. DO NOT EDIT.

package mockrepository

import (
	context "context"

	entity "github.com/Beigelman/ludaapi/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockExpenseRepository is an autogenerated mock type for the ExpenseRepository type
type MockExpenseRepository struct {
	mock.Mock
}

type MockExpenseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpenseRepository) EXPECT() *MockExpenseRepository_Expecter {
	return &MockExpenseRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockExpenseRepository) GetByID(ctx context.Context, id entity.ExpenseID) (*entity.Expense, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ExpenseID) (*entity.Expense, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ExpenseID) *entity.Expense); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ExpenseID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpenseRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockExpenseRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.ExpenseID
func (_e *MockExpenseRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockExpenseRepository_GetByID_Call {
	return &MockExpenseRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockExpenseRepository_GetByID_Call) Run(run func(ctx context.Context, id entity.ExpenseID)) *MockExpenseRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ExpenseID))
	})
	return _c
}

func (_c *MockExpenseRepository_GetByID_Call) Return(_a0 *entity.Expense, _a1 error) *MockExpenseRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpenseRepository_GetByID_Call) RunAndReturn(run func(context.Context, entity.ExpenseID) (*entity.Expense, error)) *MockExpenseRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockExpenseRepository) GetNextID() entity.ExpenseID {
	ret := _m.Called()

	var r0 entity.ExpenseID
	if rf, ok := ret.Get(0).(func() entity.ExpenseID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entity.ExpenseID)
	}

	return r0
}

// MockExpenseRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockExpenseRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockExpenseRepository_Expecter) GetNextID() *MockExpenseRepository_GetNextID_Call {
	return &MockExpenseRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockExpenseRepository_GetNextID_Call) Run(run func()) *MockExpenseRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExpenseRepository_GetNextID_Call) Return(_a0 entity.ExpenseID) *MockExpenseRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseRepository_GetNextID_Call) RunAndReturn(run func() entity.ExpenseID) *MockExpenseRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, _a1
func (_m *MockExpenseRepository) Store(ctx context.Context, _a1 *entity.Expense) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Expense) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockExpenseRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Expense
func (_e *MockExpenseRepository_Expecter) Store(ctx interface{}, _a1 interface{}) *MockExpenseRepository_Store_Call {
	return &MockExpenseRepository_Store_Call{Call: _e.mock.On("Store", ctx, _a1)}
}

func (_c *MockExpenseRepository_Store_Call) Run(run func(ctx context.Context, _a1 *entity.Expense)) *MockExpenseRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Expense))
	})
	return _c
}

func (_c *MockExpenseRepository_Store_Call) Return(_a0 error) *MockExpenseRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseRepository_Store_Call) RunAndReturn(run func(context.Context, *entity.Expense) error) *MockExpenseRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExpenseRepository creates a new instance of MockExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpenseRepository {
	mock := &MockExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
