// Code generated by mockery v2.23.4. DO NOT EDIT.

package mockservice

import (
	entity "github.com/Beigelman/nossas-despesas/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenProvider is an autogenerated mock type for the TokenProvider type
type MockTokenProvider struct {
	mock.Mock
}

type MockTokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenProvider) EXPECT() *MockTokenProvider_Expecter {
	return &MockTokenProvider_Expecter{mock: &_m.Mock}
}

// GenerateUserTokens provides a mock function with given fields: user
func (_m *MockTokenProvider) GenerateUserTokens(user entity.User) (string, string, error) {
	ret := _m.Called(user)

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(entity.User) (string, string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(entity.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(entity.User) string); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(entity.User) error); ok {
		r2 = rf(user)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTokenProvider_GenerateUserTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateUserTokens'
type MockTokenProvider_GenerateUserTokens_Call struct {
	*mock.Call
}

// GenerateUserTokens is a helper method to define mock.On call
//   - user entity.User
func (_e *MockTokenProvider_Expecter) GenerateUserTokens(user interface{}) *MockTokenProvider_GenerateUserTokens_Call {
	return &MockTokenProvider_GenerateUserTokens_Call{Call: _e.mock.On("GenerateUserTokens", user)}
}

func (_c *MockTokenProvider_GenerateUserTokens_Call) Run(run func(user entity.User)) *MockTokenProvider_GenerateUserTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.User))
	})
	return _c
}

func (_c *MockTokenProvider_GenerateUserTokens_Call) Return(_a0 string, _a1 string, _a2 error) *MockTokenProvider_GenerateUserTokens_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTokenProvider_GenerateUserTokens_Call) RunAndReturn(run func(entity.User) (string, string, error)) *MockTokenProvider_GenerateUserTokens_Call {
	_c.Call.Return(run)
	return _c
}

// ParseRefreshToken provides a mock function with given fields: token
func (_m *MockTokenProvider) ParseRefreshToken(token string) (*entity.Token, error) {
	ret := _m.Called(token)

	var r0 *entity.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.Token, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.Token); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenProvider_ParseRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseRefreshToken'
type MockTokenProvider_ParseRefreshToken_Call struct {
	*mock.Call
}

// ParseRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenProvider_Expecter) ParseRefreshToken(token interface{}) *MockTokenProvider_ParseRefreshToken_Call {
	return &MockTokenProvider_ParseRefreshToken_Call{Call: _e.mock.On("ParseRefreshToken", token)}
}

func (_c *MockTokenProvider_ParseRefreshToken_Call) Run(run func(token string)) *MockTokenProvider_ParseRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenProvider_ParseRefreshToken_Call) Return(_a0 *entity.Token, _a1 error) *MockTokenProvider_ParseRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenProvider_ParseRefreshToken_Call) RunAndReturn(run func(string) (*entity.Token, error)) *MockTokenProvider_ParseRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseToken provides a mock function with given fields: token
func (_m *MockTokenProvider) ParseToken(token string) (*entity.Token, error) {
	ret := _m.Called(token)

	var r0 *entity.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.Token, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.Token); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenProvider_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type MockTokenProvider_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenProvider_Expecter) ParseToken(token interface{}) *MockTokenProvider_ParseToken_Call {
	return &MockTokenProvider_ParseToken_Call{Call: _e.mock.On("ParseToken", token)}
}

func (_c *MockTokenProvider_ParseToken_Call) Run(run func(token string)) *MockTokenProvider_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenProvider_ParseToken_Call) Return(_a0 *entity.Token, _a1 error) *MockTokenProvider_ParseToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenProvider_ParseToken_Call) RunAndReturn(run func(string) (*entity.Token, error)) *MockTokenProvider_ParseToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenProvider creates a new instance of MockTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenProvider {
	mock := &MockTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
