// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockusecaseGenerateExpensesFromScheduledUseCase is an autogenerated mock type for the GenerateExpensesFromScheduledUseCase type
type MockusecaseGenerateExpensesFromScheduledUseCase struct {
	mock.Mock
}

type MockusecaseGenerateExpensesFromScheduledUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseGenerateExpensesFromScheduledUseCase) EXPECT() *MockusecaseGenerateExpensesFromScheduledUseCase_Expecter {
	return &MockusecaseGenerateExpensesFromScheduledUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *MockusecaseGenerateExpensesFromScheduledUseCase) Execute(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseGenerateExpensesFromScheduledUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseGenerateExpensesFromScheduledUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockusecaseGenerateExpensesFromScheduledUseCase_Expecter) Execute(ctx interface{}) *MockusecaseGenerateExpensesFromScheduledUseCase_Execute_Call {
	return &MockusecaseGenerateExpensesFromScheduledUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockusecaseGenerateExpensesFromScheduledUseCase_Execute_Call) Run(run func(ctx context.Context)) *MockusecaseGenerateExpensesFromScheduledUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockusecaseGenerateExpensesFromScheduledUseCase_Execute_Call) Return(expensesCreated int, err error) *MockusecaseGenerateExpensesFromScheduledUseCase_Execute_Call {
	_c.Call.Return(expensesCreated, err)
	return _c
}

func (_c *MockusecaseGenerateExpensesFromScheduledUseCase_Execute_Call) RunAndReturn(run func(context.Context) (int, error)) *MockusecaseGenerateExpensesFromScheduledUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseGenerateExpensesFromScheduledUseCase creates a new instance of MockusecaseGenerateExpensesFromScheduledUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseGenerateExpensesFromScheduledUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseGenerateExpensesFromScheduledUseCase {
	mock := &MockusecaseGenerateExpensesFromScheduledUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
