// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	group "github.com/Beigelman/nossas-despesas/internal/modules/group"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/group/usecase"
)

// MockusecaseInviteUserToGroup is an autogenerated mock type for the InviteUserToGroup type
type MockusecaseInviteUserToGroup struct {
	mock.Mock
}

type MockusecaseInviteUserToGroup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseInviteUserToGroup) EXPECT() *MockusecaseInviteUserToGroup_Expecter {
	return &MockusecaseInviteUserToGroup_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockusecaseInviteUserToGroup) Execute(ctx context.Context, input usecase.InviteUserToGroupInput) (*group.Invite, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *group.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.InviteUserToGroupInput) (*group.Invite, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.InviteUserToGroupInput) *group.Invite); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*group.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.InviteUserToGroupInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseInviteUserToGroup_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseInviteUserToGroup_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.InviteUserToGroupInput
func (_e *MockusecaseInviteUserToGroup_Expecter) Execute(ctx interface{}, input interface{}) *MockusecaseInviteUserToGroup_Execute_Call {
	return &MockusecaseInviteUserToGroup_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockusecaseInviteUserToGroup_Execute_Call) Run(run func(ctx context.Context, input usecase.InviteUserToGroupInput)) *MockusecaseInviteUserToGroup_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.InviteUserToGroupInput))
	})
	return _c
}

func (_c *MockusecaseInviteUserToGroup_Execute_Call) Return(_a0 *group.Invite, _a1 error) *MockusecaseInviteUserToGroup_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecaseInviteUserToGroup_Execute_Call) RunAndReturn(run func(context.Context, usecase.InviteUserToGroupInput) (*group.Invite, error)) *MockusecaseInviteUserToGroup_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseInviteUserToGroup creates a new instance of MockusecaseInviteUserToGroup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseInviteUserToGroup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseInviteUserToGroup {
	mock := &MockusecaseInviteUserToGroup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
