// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/auth/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockusecaseSignUpWithCredentials is an autogenerated mock type for the SignUpWithCredentials type
type MockusecaseSignUpWithCredentials struct {
	mock.Mock
}

type MockusecaseSignUpWithCredentials_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseSignUpWithCredentials) EXPECT() *MockusecaseSignUpWithCredentials_Expecter {
	return &MockusecaseSignUpWithCredentials_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockusecaseSignUpWithCredentials) Execute(ctx context.Context, p usecase.SignUpWithCredentialsParams) (*usecase.SignUpWithCredentialsResponse, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *usecase.SignUpWithCredentialsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.SignUpWithCredentialsParams) (*usecase.SignUpWithCredentialsResponse, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.SignUpWithCredentialsParams) *usecase.SignUpWithCredentialsResponse); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.SignUpWithCredentialsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.SignUpWithCredentialsParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseSignUpWithCredentials_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseSignUpWithCredentials_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.SignUpWithCredentialsParams
func (_e *MockusecaseSignUpWithCredentials_Expecter) Execute(ctx interface{}, p interface{}) *MockusecaseSignUpWithCredentials_Execute_Call {
	return &MockusecaseSignUpWithCredentials_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockusecaseSignUpWithCredentials_Execute_Call) Run(run func(ctx context.Context, p usecase.SignUpWithCredentialsParams)) *MockusecaseSignUpWithCredentials_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.SignUpWithCredentialsParams))
	})
	return _c
}

func (_c *MockusecaseSignUpWithCredentials_Execute_Call) Return(_a0 *usecase.SignUpWithCredentialsResponse, _a1 error) *MockusecaseSignUpWithCredentials_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecaseSignUpWithCredentials_Execute_Call) RunAndReturn(run func(context.Context, usecase.SignUpWithCredentialsParams) (*usecase.SignUpWithCredentialsResponse, error)) *MockusecaseSignUpWithCredentials_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseSignUpWithCredentials creates a new instance of MockusecaseSignUpWithCredentials. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseSignUpWithCredentials(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseSignUpWithCredentials {
	mock := &MockusecaseSignUpWithCredentials{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
