// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	expense "github.com/Beigelman/nossas-despesas/internal/modules/expense"
	mock "github.com/stretchr/testify/mock"
)

// MockexpenseScheduledExpenseRepository is an autogenerated mock type for the ScheduledExpenseRepository type
type MockexpenseScheduledExpenseRepository struct {
	mock.Mock
}

type MockexpenseScheduledExpenseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockexpenseScheduledExpenseRepository) EXPECT() *MockexpenseScheduledExpenseRepository_Expecter {
	return &MockexpenseScheduledExpenseRepository_Expecter{mock: &_m.Mock}
}

// BulkStore provides a mock function with given fields: ctx, scheduledExpenses
func (_m *MockexpenseScheduledExpenseRepository) BulkStore(ctx context.Context, scheduledExpenses []expense.ScheduledExpense) error {
	ret := _m.Called(ctx, scheduledExpenses)

	if len(ret) == 0 {
		panic("no return value specified for BulkStore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []expense.ScheduledExpense) error); ok {
		r0 = rf(ctx, scheduledExpenses)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockexpenseScheduledExpenseRepository_BulkStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkStore'
type MockexpenseScheduledExpenseRepository_BulkStore_Call struct {
	*mock.Call
}

// BulkStore is a helper method to define mock.On call
//   - ctx context.Context
//   - scheduledExpenses []expense.ScheduledExpense
func (_e *MockexpenseScheduledExpenseRepository_Expecter) BulkStore(ctx interface{}, scheduledExpenses interface{}) *MockexpenseScheduledExpenseRepository_BulkStore_Call {
	return &MockexpenseScheduledExpenseRepository_BulkStore_Call{Call: _e.mock.On("BulkStore", ctx, scheduledExpenses)}
}

func (_c *MockexpenseScheduledExpenseRepository_BulkStore_Call) Run(run func(ctx context.Context, scheduledExpenses []expense.ScheduledExpense)) *MockexpenseScheduledExpenseRepository_BulkStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]expense.ScheduledExpense))
	})
	return _c
}

func (_c *MockexpenseScheduledExpenseRepository_BulkStore_Call) Return(_a0 error) *MockexpenseScheduledExpenseRepository_BulkStore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockexpenseScheduledExpenseRepository_BulkStore_Call) RunAndReturn(run func(context.Context, []expense.ScheduledExpense) error) *MockexpenseScheduledExpenseRepository_BulkStore_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveScheduledExpenses provides a mock function with given fields: ctx
func (_m *MockexpenseScheduledExpenseRepository) GetActiveScheduledExpenses(ctx context.Context) ([]expense.ScheduledExpense, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveScheduledExpenses")
	}

	var r0 []expense.ScheduledExpense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]expense.ScheduledExpense, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []expense.ScheduledExpense); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]expense.ScheduledExpense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockexpenseScheduledExpenseRepository_GetActiveScheduledExpenses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveScheduledExpenses'
type MockexpenseScheduledExpenseRepository_GetActiveScheduledExpenses_Call struct {
	*mock.Call
}

// GetActiveScheduledExpenses is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockexpenseScheduledExpenseRepository_Expecter) GetActiveScheduledExpenses(ctx interface{}) *MockexpenseScheduledExpenseRepository_GetActiveScheduledExpenses_Call {
	return &MockexpenseScheduledExpenseRepository_GetActiveScheduledExpenses_Call{Call: _e.mock.On("GetActiveScheduledExpenses", ctx)}
}

func (_c *MockexpenseScheduledExpenseRepository_GetActiveScheduledExpenses_Call) Run(run func(ctx context.Context)) *MockexpenseScheduledExpenseRepository_GetActiveScheduledExpenses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockexpenseScheduledExpenseRepository_GetActiveScheduledExpenses_Call) Return(_a0 []expense.ScheduledExpense, _a1 error) *MockexpenseScheduledExpenseRepository_GetActiveScheduledExpenses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockexpenseScheduledExpenseRepository_GetActiveScheduledExpenses_Call) RunAndReturn(run func(context.Context) ([]expense.ScheduledExpense, error)) *MockexpenseScheduledExpenseRepository_GetActiveScheduledExpenses_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockexpenseScheduledExpenseRepository) GetByID(ctx context.Context, id expense.ScheduledExpenseID) (*expense.ScheduledExpense, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *expense.ScheduledExpense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, expense.ScheduledExpenseID) (*expense.ScheduledExpense, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, expense.ScheduledExpenseID) *expense.ScheduledExpense); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.ScheduledExpense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, expense.ScheduledExpenseID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockexpenseScheduledExpenseRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockexpenseScheduledExpenseRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id expense.ScheduledExpenseID
func (_e *MockexpenseScheduledExpenseRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockexpenseScheduledExpenseRepository_GetByID_Call {
	return &MockexpenseScheduledExpenseRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockexpenseScheduledExpenseRepository_GetByID_Call) Run(run func(ctx context.Context, id expense.ScheduledExpenseID)) *MockexpenseScheduledExpenseRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(expense.ScheduledExpenseID))
	})
	return _c
}

func (_c *MockexpenseScheduledExpenseRepository_GetByID_Call) Return(_a0 *expense.ScheduledExpense, _a1 error) *MockexpenseScheduledExpenseRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockexpenseScheduledExpenseRepository_GetByID_Call) RunAndReturn(run func(context.Context, expense.ScheduledExpenseID) (*expense.ScheduledExpense, error)) *MockexpenseScheduledExpenseRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockexpenseScheduledExpenseRepository) GetNextID() expense.ScheduledExpenseID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNextID")
	}

	var r0 expense.ScheduledExpenseID
	if rf, ok := ret.Get(0).(func() expense.ScheduledExpenseID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(expense.ScheduledExpenseID)
	}

	return r0
}

// MockexpenseScheduledExpenseRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockexpenseScheduledExpenseRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockexpenseScheduledExpenseRepository_Expecter) GetNextID() *MockexpenseScheduledExpenseRepository_GetNextID_Call {
	return &MockexpenseScheduledExpenseRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockexpenseScheduledExpenseRepository_GetNextID_Call) Run(run func()) *MockexpenseScheduledExpenseRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockexpenseScheduledExpenseRepository_GetNextID_Call) Return(_a0 expense.ScheduledExpenseID) *MockexpenseScheduledExpenseRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockexpenseScheduledExpenseRepository_GetNextID_Call) RunAndReturn(run func() expense.ScheduledExpenseID) *MockexpenseScheduledExpenseRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, entity
func (_m *MockexpenseScheduledExpenseRepository) Store(ctx context.Context, entity *expense.ScheduledExpense) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *expense.ScheduledExpense) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockexpenseScheduledExpenseRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockexpenseScheduledExpenseRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *expense.ScheduledExpense
func (_e *MockexpenseScheduledExpenseRepository_Expecter) Store(ctx interface{}, entity interface{}) *MockexpenseScheduledExpenseRepository_Store_Call {
	return &MockexpenseScheduledExpenseRepository_Store_Call{Call: _e.mock.On("Store", ctx, entity)}
}

func (_c *MockexpenseScheduledExpenseRepository_Store_Call) Run(run func(ctx context.Context, entity *expense.ScheduledExpense)) *MockexpenseScheduledExpenseRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*expense.ScheduledExpense))
	})
	return _c
}

func (_c *MockexpenseScheduledExpenseRepository_Store_Call) Return(_a0 error) *MockexpenseScheduledExpenseRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockexpenseScheduledExpenseRepository_Store_Call) RunAndReturn(run func(context.Context, *expense.ScheduledExpense) error) *MockexpenseScheduledExpenseRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockexpenseScheduledExpenseRepository creates a new instance of MockexpenseScheduledExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockexpenseScheduledExpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockexpenseScheduledExpenseRepository {
	mock := &MockexpenseScheduledExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
