// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	income "github.com/Beigelman/nossas-despesas/internal/modules/income"
	mock "github.com/stretchr/testify/mock"

	time "time"

	user "github.com/Beigelman/nossas-despesas/internal/modules/user"
)

// MockincomeRepository is an autogenerated mock type for the Repository type
type MockincomeRepository struct {
	mock.Mock
}

type MockincomeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockincomeRepository) EXPECT() *MockincomeRepository_Expecter {
	return &MockincomeRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockincomeRepository) GetByID(ctx context.Context, id income.ID) (*income.Income, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *income.Income
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, income.ID) (*income.Income, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, income.ID) *income.Income); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*income.Income)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, income.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockincomeRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockincomeRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id income.ID
func (_e *MockincomeRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockincomeRepository_GetByID_Call {
	return &MockincomeRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockincomeRepository_GetByID_Call) Run(run func(ctx context.Context, id income.ID)) *MockincomeRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(income.ID))
	})
	return _c
}

func (_c *MockincomeRepository_GetByID_Call) Return(_a0 *income.Income, _a1 error) *MockincomeRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockincomeRepository_GetByID_Call) RunAndReturn(run func(context.Context, income.ID) (*income.Income, error)) *MockincomeRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockincomeRepository) GetNextID() income.ID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNextID")
	}

	var r0 income.ID
	if rf, ok := ret.Get(0).(func() income.ID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(income.ID)
	}

	return r0
}

// MockincomeRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockincomeRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockincomeRepository_Expecter) GetNextID() *MockincomeRepository_GetNextID_Call {
	return &MockincomeRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockincomeRepository_GetNextID_Call) Run(run func()) *MockincomeRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockincomeRepository_GetNextID_Call) Return(_a0 income.ID) *MockincomeRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockincomeRepository_GetNextID_Call) RunAndReturn(run func() income.ID) *MockincomeRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserMonthlyIncomes provides a mock function with given fields: ctx, userID, date
func (_m *MockincomeRepository) GetUserMonthlyIncomes(ctx context.Context, userID user.ID, date *time.Time) ([]income.Income, error) {
	ret := _m.Called(ctx, userID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUserMonthlyIncomes")
	}

	var r0 []income.Income
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.ID, *time.Time) ([]income.Income, error)); ok {
		return rf(ctx, userID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.ID, *time.Time) []income.Income); ok {
		r0 = rf(ctx, userID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]income.Income)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.ID, *time.Time) error); ok {
		r1 = rf(ctx, userID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockincomeRepository_GetUserMonthlyIncomes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserMonthlyIncomes'
type MockincomeRepository_GetUserMonthlyIncomes_Call struct {
	*mock.Call
}

// GetUserMonthlyIncomes is a helper method to define mock.On call
//   - ctx context.Context
//   - userID user.ID
//   - date *time.Time
func (_e *MockincomeRepository_Expecter) GetUserMonthlyIncomes(ctx interface{}, userID interface{}, date interface{}) *MockincomeRepository_GetUserMonthlyIncomes_Call {
	return &MockincomeRepository_GetUserMonthlyIncomes_Call{Call: _e.mock.On("GetUserMonthlyIncomes", ctx, userID, date)}
}

func (_c *MockincomeRepository_GetUserMonthlyIncomes_Call) Run(run func(ctx context.Context, userID user.ID, date *time.Time)) *MockincomeRepository_GetUserMonthlyIncomes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.ID), args[2].(*time.Time))
	})
	return _c
}

func (_c *MockincomeRepository_GetUserMonthlyIncomes_Call) Return(_a0 []income.Income, _a1 error) *MockincomeRepository_GetUserMonthlyIncomes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockincomeRepository_GetUserMonthlyIncomes_Call) RunAndReturn(run func(context.Context, user.ID, *time.Time) ([]income.Income, error)) *MockincomeRepository_GetUserMonthlyIncomes_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, entity
func (_m *MockincomeRepository) Store(ctx context.Context, entity *income.Income) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *income.Income) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockincomeRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockincomeRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *income.Income
func (_e *MockincomeRepository_Expecter) Store(ctx interface{}, entity interface{}) *MockincomeRepository_Store_Call {
	return &MockincomeRepository_Store_Call{Call: _e.mock.On("Store", ctx, entity)}
}

func (_c *MockincomeRepository_Store_Call) Run(run func(ctx context.Context, entity *income.Income)) *MockincomeRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*income.Income))
	})
	return _c
}

func (_c *MockincomeRepository_Store_Call) Return(_a0 error) *MockincomeRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockincomeRepository_Store_Call) RunAndReturn(run func(context.Context, *income.Income) error) *MockincomeRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockincomeRepository creates a new instance of MockincomeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockincomeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockincomeRepository {
	mock := &MockincomeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
