// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/user/usecase"
	mock "github.com/stretchr/testify/mock"

	user "github.com/Beigelman/nossas-despesas/internal/modules/user"
)

// MockusecaseCreateUser is an autogenerated mock type for the CreateUser type
type MockusecaseCreateUser struct {
	mock.Mock
}

type MockusecaseCreateUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseCreateUser) EXPECT() *MockusecaseCreateUser_Expecter {
	return &MockusecaseCreateUser_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockusecaseCreateUser) Execute(ctx context.Context, p usecase.CreateUserParams) (*user.User, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateUserParams) (*user.User, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateUserParams) *user.User); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreateUserParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseCreateUser_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseCreateUser_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.CreateUserParams
func (_e *MockusecaseCreateUser_Expecter) Execute(ctx interface{}, p interface{}) *MockusecaseCreateUser_Execute_Call {
	return &MockusecaseCreateUser_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockusecaseCreateUser_Execute_Call) Run(run func(ctx context.Context, p usecase.CreateUserParams)) *MockusecaseCreateUser_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateUserParams))
	})
	return _c
}

func (_c *MockusecaseCreateUser_Execute_Call) Return(_a0 *user.User, _a1 error) *MockusecaseCreateUser_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecaseCreateUser_Execute_Call) RunAndReturn(run func(context.Context, usecase.CreateUserParams) (*user.User, error)) *MockusecaseCreateUser_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseCreateUser creates a new instance of MockusecaseCreateUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseCreateUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseCreateUser {
	mock := &MockusecaseCreateUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
