// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/expense/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockusecaseRecalculateExpensesSplitRatio is an autogenerated mock type for the RecalculateExpensesSplitRatio type
type MockusecaseRecalculateExpensesSplitRatio struct {
	mock.Mock
}

type MockusecaseRecalculateExpensesSplitRatio_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseRecalculateExpensesSplitRatio) EXPECT() *MockusecaseRecalculateExpensesSplitRatio_Expecter {
	return &MockusecaseRecalculateExpensesSplitRatio_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockusecaseRecalculateExpensesSplitRatio) Execute(ctx context.Context, input usecase.RecalculateExpensesSplitRatioInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RecalculateExpensesSplitRatioInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockusecaseRecalculateExpensesSplitRatio_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseRecalculateExpensesSplitRatio_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.RecalculateExpensesSplitRatioInput
func (_e *MockusecaseRecalculateExpensesSplitRatio_Expecter) Execute(ctx interface{}, input interface{}) *MockusecaseRecalculateExpensesSplitRatio_Execute_Call {
	return &MockusecaseRecalculateExpensesSplitRatio_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockusecaseRecalculateExpensesSplitRatio_Execute_Call) Run(run func(ctx context.Context, input usecase.RecalculateExpensesSplitRatioInput)) *MockusecaseRecalculateExpensesSplitRatio_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.RecalculateExpensesSplitRatioInput))
	})
	return _c
}

func (_c *MockusecaseRecalculateExpensesSplitRatio_Execute_Call) Return(_a0 error) *MockusecaseRecalculateExpensesSplitRatio_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockusecaseRecalculateExpensesSplitRatio_Execute_Call) RunAndReturn(run func(context.Context, usecase.RecalculateExpensesSplitRatioInput) error) *MockusecaseRecalculateExpensesSplitRatio_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseRecalculateExpensesSplitRatio creates a new instance of MockusecaseRecalculateExpensesSplitRatio. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseRecalculateExpensesSplitRatio(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseRecalculateExpensesSplitRatio {
	mock := &MockusecaseRecalculateExpensesSplitRatio{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
