// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	income "github.com/Beigelman/nossas-despesas/internal/modules/income"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/nossas-despesas/internal/modules/income/usecase"
)

// MockusecaseUpdateIncome is an autogenerated mock type for the UpdateIncome type
type MockusecaseUpdateIncome struct {
	mock.Mock
}

type MockusecaseUpdateIncome_Expecter struct {
	mock *mock.Mock
}

func (_m *MockusecaseUpdateIncome) EXPECT() *MockusecaseUpdateIncome_Expecter {
	return &MockusecaseUpdateIncome_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockusecaseUpdateIncome) Execute(ctx context.Context, p usecase.UpdateIncomeParams) (*income.Income, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *income.Income
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UpdateIncomeParams) (*income.Income, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UpdateIncomeParams) *income.Income); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*income.Income)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.UpdateIncomeParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockusecaseUpdateIncome_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockusecaseUpdateIncome_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.UpdateIncomeParams
func (_e *MockusecaseUpdateIncome_Expecter) Execute(ctx interface{}, p interface{}) *MockusecaseUpdateIncome_Execute_Call {
	return &MockusecaseUpdateIncome_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockusecaseUpdateIncome_Execute_Call) Run(run func(ctx context.Context, p usecase.UpdateIncomeParams)) *MockusecaseUpdateIncome_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.UpdateIncomeParams))
	})
	return _c
}

func (_c *MockusecaseUpdateIncome_Execute_Call) Return(_a0 *income.Income, _a1 error) *MockusecaseUpdateIncome_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockusecaseUpdateIncome_Execute_Call) RunAndReturn(run func(context.Context, usecase.UpdateIncomeParams) (*income.Income, error)) *MockusecaseUpdateIncome_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockusecaseUpdateIncome creates a new instance of MockusecaseUpdateIncome. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecaseUpdateIncome(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockusecaseUpdateIncome {
	mock := &MockusecaseUpdateIncome{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
