// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	expense "github.com/Beigelman/nossas-despesas/internal/modules/expense"
	group "github.com/Beigelman/nossas-despesas/internal/modules/group"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockexpenseRepository is an autogenerated mock type for the Repository type
type MockexpenseRepository struct {
	mock.Mock
}

type MockexpenseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockexpenseRepository) EXPECT() *MockexpenseRepository_Expecter {
	return &MockexpenseRepository_Expecter{mock: &_m.Mock}
}

// BulkStore provides a mock function with given fields: ctx, expenses
func (_m *MockexpenseRepository) BulkStore(ctx context.Context, expenses []expense.Expense) error {
	ret := _m.Called(ctx, expenses)

	if len(ret) == 0 {
		panic("no return value specified for BulkStore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []expense.Expense) error); ok {
		r0 = rf(ctx, expenses)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockexpenseRepository_BulkStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkStore'
type MockexpenseRepository_BulkStore_Call struct {
	*mock.Call
}

// BulkStore is a helper method to define mock.On call
//   - ctx context.Context
//   - expenses []expense.Expense
func (_e *MockexpenseRepository_Expecter) BulkStore(ctx interface{}, expenses interface{}) *MockexpenseRepository_BulkStore_Call {
	return &MockexpenseRepository_BulkStore_Call{Call: _e.mock.On("BulkStore", ctx, expenses)}
}

func (_c *MockexpenseRepository_BulkStore_Call) Run(run func(ctx context.Context, expenses []expense.Expense)) *MockexpenseRepository_BulkStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]expense.Expense))
	})
	return _c
}

func (_c *MockexpenseRepository_BulkStore_Call) Return(_a0 error) *MockexpenseRepository_BulkStore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockexpenseRepository_BulkStore_Call) RunAndReturn(run func(context.Context, []expense.Expense) error) *MockexpenseRepository_BulkStore_Call {
	_c.Call.Return(run)
	return _c
}

// GetByGroupDate provides a mock function with given fields: ctx, groupId, date
func (_m *MockexpenseRepository) GetByGroupDate(ctx context.Context, groupId group.ID, date time.Time) ([]expense.Expense, error) {
	ret := _m.Called(ctx, groupId, date)

	if len(ret) == 0 {
		panic("no return value specified for GetByGroupDate")
	}

	var r0 []expense.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, group.ID, time.Time) ([]expense.Expense, error)); ok {
		return rf(ctx, groupId, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, group.ID, time.Time) []expense.Expense); ok {
		r0 = rf(ctx, groupId, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]expense.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, group.ID, time.Time) error); ok {
		r1 = rf(ctx, groupId, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockexpenseRepository_GetByGroupDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByGroupDate'
type MockexpenseRepository_GetByGroupDate_Call struct {
	*mock.Call
}

// GetByGroupDate is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId group.ID
//   - date time.Time
func (_e *MockexpenseRepository_Expecter) GetByGroupDate(ctx interface{}, groupId interface{}, date interface{}) *MockexpenseRepository_GetByGroupDate_Call {
	return &MockexpenseRepository_GetByGroupDate_Call{Call: _e.mock.On("GetByGroupDate", ctx, groupId, date)}
}

func (_c *MockexpenseRepository_GetByGroupDate_Call) Run(run func(ctx context.Context, groupId group.ID, date time.Time)) *MockexpenseRepository_GetByGroupDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(group.ID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockexpenseRepository_GetByGroupDate_Call) Return(_a0 []expense.Expense, _a1 error) *MockexpenseRepository_GetByGroupDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockexpenseRepository_GetByGroupDate_Call) RunAndReturn(run func(context.Context, group.ID, time.Time) ([]expense.Expense, error)) *MockexpenseRepository_GetByGroupDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockexpenseRepository) GetByID(ctx context.Context, id expense.ID) (*expense.Expense, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *expense.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, expense.ID) (*expense.Expense, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, expense.ID) *expense.Expense); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*expense.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, expense.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockexpenseRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockexpenseRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id expense.ID
func (_e *MockexpenseRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockexpenseRepository_GetByID_Call {
	return &MockexpenseRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockexpenseRepository_GetByID_Call) Run(run func(ctx context.Context, id expense.ID)) *MockexpenseRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(expense.ID))
	})
	return _c
}

func (_c *MockexpenseRepository_GetByID_Call) Return(_a0 *expense.Expense, _a1 error) *MockexpenseRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockexpenseRepository_GetByID_Call) RunAndReturn(run func(context.Context, expense.ID) (*expense.Expense, error)) *MockexpenseRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockexpenseRepository) GetNextID() expense.ID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNextID")
	}

	var r0 expense.ID
	if rf, ok := ret.Get(0).(func() expense.ID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(expense.ID)
	}

	return r0
}

// MockexpenseRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockexpenseRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockexpenseRepository_Expecter) GetNextID() *MockexpenseRepository_GetNextID_Call {
	return &MockexpenseRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockexpenseRepository_GetNextID_Call) Run(run func()) *MockexpenseRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockexpenseRepository_GetNextID_Call) Return(_a0 expense.ID) *MockexpenseRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockexpenseRepository_GetNextID_Call) RunAndReturn(run func() expense.ID) *MockexpenseRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, entity
func (_m *MockexpenseRepository) Store(ctx context.Context, entity *expense.Expense) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *expense.Expense) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockexpenseRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockexpenseRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *expense.Expense
func (_e *MockexpenseRepository_Expecter) Store(ctx interface{}, entity interface{}) *MockexpenseRepository_Store_Call {
	return &MockexpenseRepository_Store_Call{Call: _e.mock.On("Store", ctx, entity)}
}

func (_c *MockexpenseRepository_Store_Call) Run(run func(ctx context.Context, entity *expense.Expense)) *MockexpenseRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*expense.Expense))
	})
	return _c
}

func (_c *MockexpenseRepository_Store_Call) Return(_a0 error) *MockexpenseRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockexpenseRepository_Store_Call) RunAndReturn(run func(context.Context, *expense.Expense) error) *MockexpenseRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockexpenseRepository creates a new instance of MockexpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockexpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockexpenseRepository {
	mock := &MockexpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
