// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	user "github.com/Beigelman/nossas-despesas/internal/modules/user"
	mock "github.com/stretchr/testify/mock"
)

// MockuserRepository is an autogenerated mock type for the Repository type
type MockuserRepository struct {
	mock.Mock
}

type MockuserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockuserRepository) EXPECT() *MockuserRepository_Expecter {
	return &MockuserRepository_Expecter{mock: &_m.Mock}
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *MockuserRepository) GetByEmail(ctx context.Context, email string) (*user.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockuserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockuserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockuserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockuserRepository_GetByEmail_Call {
	return &MockuserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockuserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockuserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockuserRepository_GetByEmail_Call) Return(_a0 *user.User, _a1 error) *MockuserRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockuserRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*user.User, error)) *MockuserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockuserRepository) GetByID(ctx context.Context, id user.ID) (*user.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.ID) (*user.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.ID) *user.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockuserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockuserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id user.ID
func (_e *MockuserRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockuserRepository_GetByID_Call {
	return &MockuserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockuserRepository_GetByID_Call) Run(run func(ctx context.Context, id user.ID)) *MockuserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.ID))
	})
	return _c
}

func (_c *MockuserRepository_GetByID_Call) Return(_a0 *user.User, _a1 error) *MockuserRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockuserRepository_GetByID_Call) RunAndReturn(run func(context.Context, user.ID) (*user.User, error)) *MockuserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function with given fields:
func (_m *MockuserRepository) GetNextID() user.ID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNextID")
	}

	var r0 user.ID
	if rf, ok := ret.Get(0).(func() user.ID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(user.ID)
	}

	return r0
}

// MockuserRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockuserRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
func (_e *MockuserRepository_Expecter) GetNextID() *MockuserRepository_GetNextID_Call {
	return &MockuserRepository_GetNextID_Call{Call: _e.mock.On("GetNextID")}
}

func (_c *MockuserRepository_GetNextID_Call) Run(run func()) *MockuserRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockuserRepository_GetNextID_Call) Return(_a0 user.ID) *MockuserRepository_GetNextID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockuserRepository_GetNextID_Call) RunAndReturn(run func() user.ID) *MockuserRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, entity
func (_m *MockuserRepository) Store(ctx context.Context, entity *user.User) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockuserRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockuserRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *user.User
func (_e *MockuserRepository_Expecter) Store(ctx interface{}, entity interface{}) *MockuserRepository_Store_Call {
	return &MockuserRepository_Store_Call{Call: _e.mock.On("Store", ctx, entity)}
}

func (_c *MockuserRepository_Store_Call) Run(run func(ctx context.Context, entity *user.User)) *MockuserRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*user.User))
	})
	return _c
}

func (_c *MockuserRepository_Store_Call) Return(_a0 error) *MockuserRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockuserRepository_Store_Call) RunAndReturn(run func(context.Context, *user.User) error) *MockuserRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockuserRepository creates a new instance of MockuserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockuserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockuserRepository {
	mock := &MockuserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
