// Code generated by mockery v2.23.4. DO NOT EDIT.

package mockusecase

import (
	context "context"

	entity "github.com/Beigelman/nossas-despesas/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/nossas-despesas/internal/usecase"
)

// MockCreateCategory is an autogenerated mock type for the CreateCategory type
type MockCreateCategory struct {
	mock.Mock
}

type MockCreateCategory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateCategory) EXPECT() *MockCreateCategory_Expecter {
	return &MockCreateCategory_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockCreateCategory) Execute(ctx context.Context, input usecase.CreateCategoryInput) (*entity.Category, error) {
	ret := _m.Called(ctx, input)

	var r0 *entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateCategoryInput) (*entity.Category, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateCategoryInput) *entity.Category); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreateCategoryInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateCategory_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateCategory_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.CreateCategoryInput
func (_e *MockCreateCategory_Expecter) Execute(ctx interface{}, input interface{}) *MockCreateCategory_Execute_Call {
	return &MockCreateCategory_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockCreateCategory_Execute_Call) Run(run func(ctx context.Context, input usecase.CreateCategoryInput)) *MockCreateCategory_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateCategoryInput))
	})
	return _c
}

func (_c *MockCreateCategory_Execute_Call) Return(_a0 *entity.Category, _a1 error) *MockCreateCategory_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateCategory_Execute_Call) RunAndReturn(run func(context.Context, usecase.CreateCategoryInput) (*entity.Category, error)) *MockCreateCategory_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateCategory creates a new instance of MockCreateCategory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateCategory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateCategory {
	mock := &MockCreateCategory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
