// Code generated by mockery v2.35.2. DO NOT EDIT.

package mockusecase

import (
	context "context"

	entity "github.com/Beigelman/nossas-despesas/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/nossas-despesas/internal/usecase"
)

// MockUpdateExpense is an autogenerated mock type for the UpdateExpense type
type MockUpdateExpense struct {
	mock.Mock
}

type MockUpdateExpense_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateExpense) EXPECT() *MockUpdateExpense_Expecter {
	return &MockUpdateExpense_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockUpdateExpense) Execute(ctx context.Context, p usecase.UpdateExpenseParams) (*entity.Expense, error) {
	ret := _m.Called(ctx, p)

	var r0 *entity.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UpdateExpenseParams) (*entity.Expense, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UpdateExpenseParams) *entity.Expense); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.UpdateExpenseParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateExpense_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateExpense_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.UpdateExpenseParams
func (_e *MockUpdateExpense_Expecter) Execute(ctx interface{}, p interface{}) *MockUpdateExpense_Execute_Call {
	return &MockUpdateExpense_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockUpdateExpense_Execute_Call) Run(run func(ctx context.Context, p usecase.UpdateExpenseParams)) *MockUpdateExpense_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.UpdateExpenseParams))
	})
	return _c
}

func (_c *MockUpdateExpense_Execute_Call) Return(_a0 *entity.Expense, _a1 error) *MockUpdateExpense_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateExpense_Execute_Call) RunAndReturn(run func(context.Context, usecase.UpdateExpenseParams) (*entity.Expense, error)) *MockUpdateExpense_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateExpense creates a new instance of MockUpdateExpense. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateExpense(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateExpense {
	mock := &MockUpdateExpense{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
