// Code generated by mockery v2.43.2. DO NOT EDIT.

package mockusecase

import (
	context "context"

	entity "github.com/Beigelman/nossas-despesas/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockDeleteExpense is an autogenerated mock type for the DeleteExpense type
type MockDeleteExpense struct {
	mock.Mock
}

type MockDeleteExpense_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteExpense) EXPECT() *MockDeleteExpense_Expecter {
	return &MockDeleteExpense_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, expenseID
func (_m *MockDeleteExpense) Execute(ctx context.Context, expenseID entity.ExpenseID) (*entity.Expense, error) {
	ret := _m.Called(ctx, expenseID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entity.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ExpenseID) (*entity.Expense, error)); ok {
		return rf(ctx, expenseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ExpenseID) *entity.Expense); ok {
		r0 = rf(ctx, expenseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ExpenseID) error); ok {
		r1 = rf(ctx, expenseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeleteExpense_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDeleteExpense_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - expenseID entity.ExpenseID
func (_e *MockDeleteExpense_Expecter) Execute(ctx interface{}, expenseID interface{}) *MockDeleteExpense_Execute_Call {
	return &MockDeleteExpense_Execute_Call{Call: _e.mock.On("Execute", ctx, expenseID)}
}

func (_c *MockDeleteExpense_Execute_Call) Run(run func(ctx context.Context, expenseID entity.ExpenseID)) *MockDeleteExpense_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ExpenseID))
	})
	return _c
}

func (_c *MockDeleteExpense_Execute_Call) Return(_a0 *entity.Expense, _a1 error) *MockDeleteExpense_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeleteExpense_Execute_Call) RunAndReturn(run func(context.Context, entity.ExpenseID) (*entity.Expense, error)) *MockDeleteExpense_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteExpense creates a new instance of MockDeleteExpense. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteExpense(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteExpense {
	mock := &MockDeleteExpense{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
