// Code generated by mockery v2.43.2. DO NOT EDIT.

package mockusecase

import (
	context "context"
	entity "github.com/Beigelman/nossas-despesas/internal/modules/income"
	"github.com/Beigelman/nossas-despesas/internal/modules/income/usecase"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdateIncome is an autogenerated mock type for the UpdateIncome type
type MockUpdateIncome struct {
	mock.Mock
}

type MockUpdateIncome_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateIncome) EXPECT() *MockUpdateIncome_Expecter {
	return &MockUpdateIncome_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockUpdateIncome) Execute(ctx context.Context, p usecase.UpdateIncomeParams) (*entity.Income, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entity.Income
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UpdateIncomeParams) (*entity.Income, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UpdateIncomeParams) *entity.Income); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Income)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.UpdateIncomeParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateIncome_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateIncome_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.UpdateIncomeParams
func (_e *MockUpdateIncome_Expecter) Execute(ctx interface{}, p interface{}) *MockUpdateIncome_Execute_Call {
	return &MockUpdateIncome_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockUpdateIncome_Execute_Call) Run(run func(ctx context.Context, p usecase.UpdateIncomeParams)) *MockUpdateIncome_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.UpdateIncomeParams))
	})
	return _c
}

func (_c *MockUpdateIncome_Execute_Call) Return(_a0 *entity.Income, _a1 error) *MockUpdateIncome_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateIncome_Execute_Call) RunAndReturn(run func(context.Context, usecase.UpdateIncomeParams) (*entity.Income, error)) *MockUpdateIncome_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateIncome creates a new instance of MockUpdateIncome. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateIncome(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateIncome {
	mock := &MockUpdateIncome{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
