// Code generated by mockery v2.23.4. DO NOT EDIT.

package mockusecase

import (
	context "context"

	entity "github.com/Beigelman/ludaapi/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/ludaapi/internal/usecase"
)

// MockCreateIncome is an autogenerated mock type for the CreateIncome type
type MockCreateIncome struct {
	mock.Mock
}

type MockCreateIncome_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateIncome) EXPECT() *MockCreateIncome_Expecter {
	return &MockCreateIncome_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockCreateIncome) Execute(ctx context.Context, p usecase.CreateIncomeParams) (*entity.Income, error) {
	ret := _m.Called(ctx, p)

	var r0 *entity.Income
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateIncomeParams) (*entity.Income, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateIncomeParams) *entity.Income); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Income)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreateIncomeParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateIncome_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateIncome_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.CreateIncomeParams
func (_e *MockCreateIncome_Expecter) Execute(ctx interface{}, p interface{}) *MockCreateIncome_Execute_Call {
	return &MockCreateIncome_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockCreateIncome_Execute_Call) Run(run func(ctx context.Context, p usecase.CreateIncomeParams)) *MockCreateIncome_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateIncomeParams))
	})
	return _c
}

func (_c *MockCreateIncome_Execute_Call) Return(_a0 *entity.Income, _a1 error) *MockCreateIncome_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateIncome_Execute_Call) RunAndReturn(run func(context.Context, usecase.CreateIncomeParams) (*entity.Income, error)) *MockCreateIncome_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateIncome creates a new instance of MockCreateIncome. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateIncome(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateIncome {
	mock := &MockCreateIncome{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
