// Code generated by mockery v2.23.4. DO NOT EDIT.

package mockusecase

import (
	context "context"

	entity "github.com/Beigelman/nossas-despesas/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/nossas-despesas/internal/usecase"
)

// MockCreateExpense is an autogenerated mock type for the CreateExpense type
type MockCreateExpense struct {
	mock.Mock
}

type MockCreateExpense_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateExpense) EXPECT() *MockCreateExpense_Expecter {
	return &MockCreateExpense_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockCreateExpense) Execute(ctx context.Context, p usecase.CreateExpenseParams) (*entity.Expense, error) {
	ret := _m.Called(ctx, p)

	var r0 *entity.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateExpenseParams) (*entity.Expense, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateExpenseParams) *entity.Expense); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreateExpenseParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateExpense_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateExpense_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.CreateExpenseParams
func (_e *MockCreateExpense_Expecter) Execute(ctx interface{}, p interface{}) *MockCreateExpense_Execute_Call {
	return &MockCreateExpense_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockCreateExpense_Execute_Call) Run(run func(ctx context.Context, p usecase.CreateExpenseParams)) *MockCreateExpense_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateExpenseParams))
	})
	return _c
}

func (_c *MockCreateExpense_Execute_Call) Return(_a0 *entity.Expense, _a1 error) *MockCreateExpense_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateExpense_Execute_Call) RunAndReturn(run func(context.Context, usecase.CreateExpenseParams) (*entity.Expense, error)) *MockCreateExpense_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateExpense creates a new instance of MockCreateExpense. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateExpense(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateExpense {
	mock := &MockCreateExpense{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
