// Code generated by mockery v2.23.4. DO NOT EDIT.

package mockusecase

import (
	context "context"

	usecase "github.com/Beigelman/ludaapi/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockSignInWithGoogle is an autogenerated mock type for the SignInWithGoogle type
type MockSignInWithGoogle struct {
	mock.Mock
}

type MockSignInWithGoogle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSignInWithGoogle) EXPECT() *MockSignInWithGoogle_Expecter {
	return &MockSignInWithGoogle_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockSignInWithGoogle) Execute(ctx context.Context, p usecase.SignInWithGoogleParams) (*usecase.SignInWithGoogleResponse, error) {
	ret := _m.Called(ctx, p)

	var r0 *usecase.SignInWithGoogleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.SignInWithGoogleParams) (*usecase.SignInWithGoogleResponse, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.SignInWithGoogleParams) *usecase.SignInWithGoogleResponse); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.SignInWithGoogleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.SignInWithGoogleParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSignInWithGoogle_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSignInWithGoogle_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.SignInWithGoogleParams
func (_e *MockSignInWithGoogle_Expecter) Execute(ctx interface{}, p interface{}) *MockSignInWithGoogle_Execute_Call {
	return &MockSignInWithGoogle_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockSignInWithGoogle_Execute_Call) Run(run func(ctx context.Context, p usecase.SignInWithGoogleParams)) *MockSignInWithGoogle_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.SignInWithGoogleParams))
	})
	return _c
}

func (_c *MockSignInWithGoogle_Execute_Call) Return(_a0 *usecase.SignInWithGoogleResponse, _a1 error) *MockSignInWithGoogle_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSignInWithGoogle_Execute_Call) RunAndReturn(run func(context.Context, usecase.SignInWithGoogleParams) (*usecase.SignInWithGoogleResponse, error)) *MockSignInWithGoogle_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSignInWithGoogle creates a new instance of MockSignInWithGoogle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSignInWithGoogle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSignInWithGoogle {
	mock := &MockSignInWithGoogle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
