// Code generated by mockery v2.23.4. DO NOT EDIT.

package mockusecase

import (
	context "context"

	usecase "github.com/Beigelman/nossas-despesas/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockAcceptGroupInvite is an autogenerated mock type for the AcceptGroupInvite type
type MockAcceptGroupInvite struct {
	mock.Mock
}

type MockAcceptGroupInvite_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAcceptGroupInvite) EXPECT() *MockAcceptGroupInvite_Expecter {
	return &MockAcceptGroupInvite_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockAcceptGroupInvite) Execute(ctx context.Context, input usecase.AcceptGroupInviteInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.AcceptGroupInviteInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAcceptGroupInvite_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAcceptGroupInvite_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.AcceptGroupInviteInput
func (_e *MockAcceptGroupInvite_Expecter) Execute(ctx interface{}, input interface{}) *MockAcceptGroupInvite_Execute_Call {
	return &MockAcceptGroupInvite_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockAcceptGroupInvite_Execute_Call) Run(run func(ctx context.Context, input usecase.AcceptGroupInviteInput)) *MockAcceptGroupInvite_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.AcceptGroupInviteInput))
	})
	return _c
}

func (_c *MockAcceptGroupInvite_Execute_Call) Return(_a0 error) *MockAcceptGroupInvite_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAcceptGroupInvite_Execute_Call) RunAndReturn(run func(context.Context, usecase.AcceptGroupInviteInput) error) *MockAcceptGroupInvite_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAcceptGroupInvite creates a new instance of MockAcceptGroupInvite. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAcceptGroupInvite(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAcceptGroupInvite {
	mock := &MockAcceptGroupInvite{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
