// Code generated by mockery v2.43.2. DO NOT EDIT.

package mockusecase

import (
	context "context"

	entity "github.com/Beigelman/nossas-despesas/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/nossas-despesas/internal/usecase"
)

// MockInviteUserToGroup is an autogenerated mock type for the InviteUserToGroup type
type MockInviteUserToGroup struct {
	mock.Mock
}

type MockInviteUserToGroup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInviteUserToGroup) EXPECT() *MockInviteUserToGroup_Expecter {
	return &MockInviteUserToGroup_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockInviteUserToGroup) Execute(ctx context.Context, input usecase.InviteUserToGroupInput) (*entity.GroupInvite, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entity.GroupInvite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.InviteUserToGroupInput) (*entity.GroupInvite, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.InviteUserToGroupInput) *entity.GroupInvite); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.GroupInvite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.InviteUserToGroupInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInviteUserToGroup_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockInviteUserToGroup_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.InviteUserToGroupInput
func (_e *MockInviteUserToGroup_Expecter) Execute(ctx interface{}, input interface{}) *MockInviteUserToGroup_Execute_Call {
	return &MockInviteUserToGroup_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockInviteUserToGroup_Execute_Call) Run(run func(ctx context.Context, input usecase.InviteUserToGroupInput)) *MockInviteUserToGroup_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.InviteUserToGroupInput))
	})
	return _c
}

func (_c *MockInviteUserToGroup_Execute_Call) Return(_a0 *entity.GroupInvite, _a1 error) *MockInviteUserToGroup_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInviteUserToGroup_Execute_Call) RunAndReturn(run func(context.Context, usecase.InviteUserToGroupInput) (*entity.GroupInvite, error)) *MockInviteUserToGroup_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInviteUserToGroup creates a new instance of MockInviteUserToGroup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInviteUserToGroup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInviteUserToGroup {
	mock := &MockInviteUserToGroup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
