// Code generated by mockery v2.35.2. DO NOT EDIT.

package mockusecase

import (
	context "context"

	usecase "github.com/Beigelman/nossas-despesas/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockRefreshAuthToken is an autogenerated mock type for the RefreshAuthToken type
type MockRefreshAuthToken struct {
	mock.Mock
}

type MockRefreshAuthToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshAuthToken) EXPECT() *MockRefreshAuthToken_Expecter {
	return &MockRefreshAuthToken_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockRefreshAuthToken) Execute(ctx context.Context, p usecase.RefreshAuthTokenParams) (*usecase.RefreshAuthTokenResponse, error) {
	ret := _m.Called(ctx, p)

	var r0 *usecase.RefreshAuthTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RefreshAuthTokenParams) (*usecase.RefreshAuthTokenResponse, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RefreshAuthTokenParams) *usecase.RefreshAuthTokenResponse); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.RefreshAuthTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.RefreshAuthTokenParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshAuthToken_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockRefreshAuthToken_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.RefreshAuthTokenParams
func (_e *MockRefreshAuthToken_Expecter) Execute(ctx interface{}, p interface{}) *MockRefreshAuthToken_Execute_Call {
	return &MockRefreshAuthToken_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockRefreshAuthToken_Execute_Call) Run(run func(ctx context.Context, p usecase.RefreshAuthTokenParams)) *MockRefreshAuthToken_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.RefreshAuthTokenParams))
	})
	return _c
}

func (_c *MockRefreshAuthToken_Execute_Call) Return(_a0 *usecase.RefreshAuthTokenResponse, _a1 error) *MockRefreshAuthToken_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshAuthToken_Execute_Call) RunAndReturn(run func(context.Context, usecase.RefreshAuthTokenParams) (*usecase.RefreshAuthTokenResponse, error)) *MockRefreshAuthToken_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshAuthToken creates a new instance of MockRefreshAuthToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshAuthToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshAuthToken {
	mock := &MockRefreshAuthToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
