// Code generated by mockery v2.23.4. DO NOT EDIT.

package mockusecase

import (
	context "context"

	entity "github.com/Beigelman/ludaapi/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/ludaapi/internal/usecase"
)

// MockCreateCategoryGroup is an autogenerated mock type for the CreateCategoryGroup type
type MockCreateCategoryGroup struct {
	mock.Mock
}

type MockCreateCategoryGroup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateCategoryGroup) EXPECT() *MockCreateCategoryGroup_Expecter {
	return &MockCreateCategoryGroup_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockCreateCategoryGroup) Execute(ctx context.Context, input usecase.CreateCategoryGroupInput) (*entity.CategoryGroup, error) {
	ret := _m.Called(ctx, input)

	var r0 *entity.CategoryGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateCategoryGroupInput) (*entity.CategoryGroup, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateCategoryGroupInput) *entity.CategoryGroup); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CategoryGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreateCategoryGroupInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateCategoryGroup_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateCategoryGroup_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.CreateCategoryGroupInput
func (_e *MockCreateCategoryGroup_Expecter) Execute(ctx interface{}, input interface{}) *MockCreateCategoryGroup_Execute_Call {
	return &MockCreateCategoryGroup_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockCreateCategoryGroup_Execute_Call) Run(run func(ctx context.Context, input usecase.CreateCategoryGroupInput)) *MockCreateCategoryGroup_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateCategoryGroupInput))
	})
	return _c
}

func (_c *MockCreateCategoryGroup_Execute_Call) Return(_a0 *entity.CategoryGroup, _a1 error) *MockCreateCategoryGroup_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateCategoryGroup_Execute_Call) RunAndReturn(run func(context.Context, usecase.CreateCategoryGroupInput) (*entity.CategoryGroup, error)) *MockCreateCategoryGroup_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateCategoryGroup creates a new instance of MockCreateCategoryGroup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateCategoryGroup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateCategoryGroup {
	mock := &MockCreateCategoryGroup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
