// Code generated by mockery v2.35.2. DO NOT EDIT.

package mockusecase

import (
	context "context"

	usecase "github.com/Beigelman/nossas-despesas/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockRecalculateExpensesSplitRatio is an autogenerated mock type for the RecalculateExpensesSplitRatio type
type MockRecalculateExpensesSplitRatio struct {
	mock.Mock
}

type MockRecalculateExpensesSplitRatio_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecalculateExpensesSplitRatio) EXPECT() *MockRecalculateExpensesSplitRatio_Expecter {
	return &MockRecalculateExpensesSplitRatio_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockRecalculateExpensesSplitRatio) Execute(ctx context.Context, input usecase.RecalculateExpensesSplitRatioInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RecalculateExpensesSplitRatioInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRecalculateExpensesSplitRatio_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockRecalculateExpensesSplitRatio_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.RecalculateExpensesSplitRatioInput
func (_e *MockRecalculateExpensesSplitRatio_Expecter) Execute(ctx interface{}, input interface{}) *MockRecalculateExpensesSplitRatio_Execute_Call {
	return &MockRecalculateExpensesSplitRatio_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockRecalculateExpensesSplitRatio_Execute_Call) Run(run func(ctx context.Context, input usecase.RecalculateExpensesSplitRatioInput)) *MockRecalculateExpensesSplitRatio_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.RecalculateExpensesSplitRatioInput))
	})
	return _c
}

func (_c *MockRecalculateExpensesSplitRatio_Execute_Call) Return(_a0 error) *MockRecalculateExpensesSplitRatio_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRecalculateExpensesSplitRatio_Execute_Call) RunAndReturn(run func(context.Context, usecase.RecalculateExpensesSplitRatioInput) error) *MockRecalculateExpensesSplitRatio_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRecalculateExpensesSplitRatio creates a new instance of MockRecalculateExpensesSplitRatio. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecalculateExpensesSplitRatio(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecalculateExpensesSplitRatio {
	mock := &MockRecalculateExpensesSplitRatio{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
