// Code generated by mockery v2.23.4. DO NOT EDIT.

package mockusecase

import (
	context "context"

	entity "github.com/Beigelman/nossas-despesas/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/Beigelman/nossas-despesas/internal/usecase"
)

// MockAddUserToGroup is an autogenerated mock type for the AddUserToGroup type
type MockAddUserToGroup struct {
	mock.Mock
}

type MockAddUserToGroup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAddUserToGroup) EXPECT() *MockAddUserToGroup_Expecter {
	return &MockAddUserToGroup_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockAddUserToGroup) Execute(ctx context.Context, input usecase.AddUserToGroupInput) (*entity.User, error) {
	ret := _m.Called(ctx, input)

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.AddUserToGroupInput) (*entity.User, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.AddUserToGroupInput) *entity.User); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.AddUserToGroupInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAddUserToGroup_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAddUserToGroup_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.AddUserToGroupInput
func (_e *MockAddUserToGroup_Expecter) Execute(ctx interface{}, input interface{}) *MockAddUserToGroup_Execute_Call {
	return &MockAddUserToGroup_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockAddUserToGroup_Execute_Call) Run(run func(ctx context.Context, input usecase.AddUserToGroupInput)) *MockAddUserToGroup_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.AddUserToGroupInput))
	})
	return _c
}

func (_c *MockAddUserToGroup_Execute_Call) Return(_a0 *entity.User, _a1 error) *MockAddUserToGroup_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAddUserToGroup_Execute_Call) RunAndReturn(run func(context.Context, usecase.AddUserToGroupInput) (*entity.User, error)) *MockAddUserToGroup_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAddUserToGroup creates a new instance of MockAddUserToGroup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAddUserToGroup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAddUserToGroup {
	mock := &MockAddUserToGroup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
