// Code generated by mockery v2.35.2. DO NOT EDIT.

package mockusecase

import (
	context "context"

	usecase "github.com/Beigelman/nossas-despesas/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockSignInWithCredentials is an autogenerated mock type for the SignInWithCredentials type
type MockSignInWithCredentials struct {
	mock.Mock
}

type MockSignInWithCredentials_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSignInWithCredentials) EXPECT() *MockSignInWithCredentials_Expecter {
	return &MockSignInWithCredentials_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, p
func (_m *MockSignInWithCredentials) Execute(ctx context.Context, p usecase.SignInWithCredentialsParams) (*usecase.SignInWithCredentialsResponse, error) {
	ret := _m.Called(ctx, p)

	var r0 *usecase.SignInWithCredentialsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.SignInWithCredentialsParams) (*usecase.SignInWithCredentialsResponse, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.SignInWithCredentialsParams) *usecase.SignInWithCredentialsResponse); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.SignInWithCredentialsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.SignInWithCredentialsParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSignInWithCredentials_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSignInWithCredentials_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p usecase.SignInWithCredentialsParams
func (_e *MockSignInWithCredentials_Expecter) Execute(ctx interface{}, p interface{}) *MockSignInWithCredentials_Execute_Call {
	return &MockSignInWithCredentials_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockSignInWithCredentials_Execute_Call) Run(run func(ctx context.Context, p usecase.SignInWithCredentialsParams)) *MockSignInWithCredentials_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.SignInWithCredentialsParams))
	})
	return _c
}

func (_c *MockSignInWithCredentials_Execute_Call) Return(_a0 *usecase.SignInWithCredentialsResponse, _a1 error) *MockSignInWithCredentials_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSignInWithCredentials_Execute_Call) RunAndReturn(run func(context.Context, usecase.SignInWithCredentialsParams) (*usecase.SignInWithCredentialsResponse, error)) *MockSignInWithCredentials_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSignInWithCredentials creates a new instance of MockSignInWithCredentials. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSignInWithCredentials(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSignInWithCredentials {
	mock := &MockSignInWithCredentials{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
